    CLADE : fishes 
    SPEC_NAME : AnaAna 
    FULL_SPEC_NAME : Anableps_anableps 
    ALN_NAME : fAnaAna 
    CHROM_START_CHR : CM
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 24
    NUM_ALL_CHR: 24
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM026065.1
        - CM026066.1
        - CM026067.1
        - CM026068.1
        - CM026069.1
        - CM026070.1
        - CM026071.1
        - CM026072.1
        - CM026073.1
        - CM026074.1
        - CM026075.1
        - CM026076.1
        - CM026077.1
        - CM026078.1
        - CM026079.1
        - CM026080.1
        - CM026081.1
        - CM026082.1
        - CM026083.1
        - CM026084.1
        - CM026085.1
        - CM026086.1
        - CM026087.1
        - CM026088.1
    AUTOSOMAL_CHROMOSOMES: 
        - CM026065.1
        - CM026066.1
        - CM026067.1
        - CM026068.1
        - CM026069.1
        - CM026070.1
        - CM026071.1
        - CM026072.1
        - CM026073.1
        - CM026074.1
        - CM026075.1
        - CM026076.1
        - CM026077.1
        - CM026078.1
        - CM026079.1
        - CM026080.1
        - CM026081.1
        - CM026082.1
        - CM026083.1
        - CM026084.1
        - CM026085.1
        - CM026086.1
        - CM026087.1
        - CM026088.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
