    CLADE : fishes 
    SPEC_NAME : AstMex 
    FULL_SPEC_NAME : Astyanax_mexicanus 
    ALN_NAME : fAstMex 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 25
    NUM_ALL_CHR: 25
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_064408.1
        - NC_064409.1
        - NC_064410.1
        - NC_064411.1
        - NC_064412.1
        - NC_064413.1
        - NC_064414.1
        - NC_064415.1
        - NC_064416.1
        - NC_064417.1
        - NC_064418.1
        - NC_064419.1
        - NC_064420.1
        - NC_064421.1
        - NC_064422.1
        - NC_064423.1
        - NC_064424.1
        - NC_064425.1
        - NC_064426.1
        - NC_064427.1
        - NC_064428.1
        - NC_064429.1
        - NC_064430.1
        - NC_064431.1
        - NC_064432.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_064408.1
        - NC_064409.1
        - NC_064410.1
        - NC_064411.1
        - NC_064412.1
        - NC_064413.1
        - NC_064414.1
        - NC_064415.1
        - NC_064416.1
        - NC_064417.1
        - NC_064418.1
        - NC_064419.1
        - NC_064420.1
        - NC_064421.1
        - NC_064422.1
        - NC_064423.1
        - NC_064424.1
        - NC_064425.1
        - NC_064426.1
        - NC_064427.1
        - NC_064428.1
        - NC_064429.1
        - NC_064430.1
        - NC_064431.1
        - NC_064432.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
