    CLADE : fishes 
    SPEC_NAME : ChaCha 
    FULL_SPEC_NAME : Chanos_chanos 
    ALN_NAME : fChaCha 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 16
    NUM_ALL_CHR: 16
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_044495.1
        - NC_044496.1
        - NC_044497.1
        - NC_044498.1
        - NC_044499.1
        - NC_044500.1
        - NC_044501.1
        - NC_044502.1
        - NC_044503.1
        - NC_044504.1
        - NC_044505.1
        - NC_044506.1
        - NC_044507.1
        - NC_044508.1
        - NC_044509.1
        - NC_044510.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_044495.1
        - NC_044496.1
        - NC_044497.1
        - NC_044498.1
        - NC_044499.1
        - NC_044500.1
        - NC_044501.1
        - NC_044502.1
        - NC_044503.1
        - NC_044504.1
        - NC_044505.1
        - NC_044506.1
        - NC_044507.1
        - NC_044508.1
        - NC_044509.1
        - NC_044510.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
