    CLADE : fishes 
    SPEC_NAME : CycLum 
    FULL_SPEC_NAME: "Cyclopterus_lumpus"
    ALN_NAME: "fCycLum"
    REF_NAME : GCF_009769545.1 
    ALT_NAME : GCA_963457625.1 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 25
    NUM_ALL_CHR: 25
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 5
    ALL_CHROMOSOMES : 
        - NC_046966.1
        - NC_046967.1
        - NC_046968.1
        - NC_046969.1
        - NC_046970.1
        - NC_046971.1
        - NC_046972.1
        - NC_046973.1
        - NC_046974.1
        - NC_046975.1
        - NC_046976.1
        - NC_046977.1
        - NC_046978.1
        - NC_046979.1
        - NC_046980.1
        - NC_046981.1
        - NC_046982.1
        - NC_046983.1
        - NC_046984.1
        - NC_046985.1
        - NC_046986.1
        - NC_046987.1
        - NC_046988.1
        - NC_046989.1
        - NC_046990.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_046966.1
        - NC_046967.1
        - NC_046968.1
        - NC_046969.1
        - NC_046970.1
        - NC_046971.1
        - NC_046972.1
        - NC_046973.1
        - NC_046974.1
        - NC_046975.1
        - NC_046976.1
        - NC_046977.1
        - NC_046978.1
        - NC_046979.1
        - NC_046980.1
        - NC_046981.1
        - NC_046982.1
        - NC_046983.1
        - NC_046984.1
        - NC_046985.1
        - NC_046986.1
        - NC_046987.1
        - NC_046988.1
        - NC_046989.1
        - NC_046990.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
