    CLADE : fishes 
    SPEC_NAME : EleAnt 
    FULL_SPEC_NAME : Electrona_antarctica 
    ALN_NAME : fEleAnt 
    CHROM_START_CHR : OX
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 24
    NUM_ALL_CHR: 24
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - OX578246.1
        - OX578247.1
        - OX578248.1
        - OX578249.1
        - OX578250.1
        - OX578251.1
        - OX578252.1
        - OX578253.1
        - OX578254.1
        - OX578255.1
        - OX578256.1
        - OX578257.1
        - OX578258.1
        - OX578259.1
        - OX578260.1
        - OX578261.1
        - OX578262.1
        - OX578263.1
        - OX578264.1
        - OX578265.1
        - OX578266.1
        - OX578267.1
        - OX578268.1
        - OX578269.1
    AUTOSOMAL_CHROMOSOMES: 
        - OX578246.1
        - OX578247.1
        - OX578248.1
        - OX578249.1
        - OX578250.1
        - OX578251.1
        - OX578252.1
        - OX578253.1
        - OX578254.1
        - OX578255.1
        - OX578256.1
        - OX578257.1
        - OX578258.1
        - OX578259.1
        - OX578260.1
        - OX578261.1
        - OX578262.1
        - OX578263.1
        - OX578264.1
        - OX578265.1
        - OX578266.1
        - OX578267.1
        - OX578268.1
        - OX578269.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
