    CLADE : fishes
    SPEC_NAME : EleEle 
    FULL_SPEC_NAME: Electrophorus_electricus
    ALN_NAME: fEleEle
    REF_NAME : GCA_041902795.1 
    ALT_NAME : GCA_013358815.1 
    CHROM_START_CHR : CM
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 26
    NUM_ALL_CHR: 26
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 3.5
    ALL_CHROMOSOMES : 
        - CM085978.1
        - CM085979.1
        - CM085980.1
        - CM085981.1
        - CM085982.1
        - CM085983.1
        - CM085984.1
        - CM085985.1
        - CM085986.1
        - CM085987.1
        - CM085988.1
        - CM085989.1
        - CM085990.1
        - CM085991.1
        - CM085992.1
        - CM085993.1
        - CM085994.1
        - CM085995.1
        - CM085996.1
        - CM085997.1
        - CM085998.1
        - CM085999.1
        - CM086000.1
        - CM086001.1
        - CM086002.1
        - CM086003.1
    AUTOSOMAL_CHROMOSOMES: 
        - CM085978.1
        - CM085979.1
        - CM085980.1
        - CM085981.1
        - CM085982.1
        - CM085983.1
        - CM085984.1
        - CM085985.1
        - CM085986.1
        - CM085987.1
        - CM085988.1
        - CM085989.1
        - CM085990.1
        - CM085991.1
        - CM085992.1
        - CM085993.1
        - CM085994.1
        - CM085995.1
        - CM085996.1
        - CM085997.1
        - CM085998.1
        - CM085999.1
        - CM086000.1
        - CM086001.1
        - CM086002.1
        - CM086003.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
