    CLADE : fishes 
    SPEC_NAME : GirMul 
    FULL_SPEC_NAME : Girardinichthys_multiradiatus 
    ALN_NAME : fGirMul 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 24
    NUM_ALL_CHR: 26
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_061794.1
        - NC_061795.1
        - NC_061796.1
        - NC_061797.1
        - NC_061798.1
        - NC_061799.1
        - NC_061800.1
        - NC_061801.1
        - NC_061802.1
        - NC_061803.1
        - NC_061804.1
        - NC_061805.1
        - NC_061806.1
        - NC_061807.1
        - NC_061808.1
        - NC_061809.1
        - NC_061810.1
        - NC_061811.1
        - NC_061812.1
        - NC_061813.1
        - NC_061814.1
        - NC_061815.1
        - NC_061816.1
        - NC_061817.1
        - NC_061818.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_061794.1
        - NC_061795.1
        - NC_061796.1
        - NC_061797.1
        - NC_061798.1
        - NC_061799.1
        - NC_061800.1
        - NC_061801.1
        - NC_061802.1
        - NC_061803.1
        - NC_061804.1
        - NC_061805.1
        - NC_061806.1
        - NC_061807.1
        - NC_061808.1
        - NC_061809.1
        - NC_061810.1
        - NC_061811.1
        - NC_061812.1
        - NC_061813.1
        - NC_061814.1
        - NC_061815.1
        - NC_061816.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
