    CLADE : fishes 
    SPEC_NAME : GobGob 
    FULL_SPEC_NAME : Gobio_gobio 
    ALN_NAME : fGobGob 
    CHROM_START_CHR : OX
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 25
    NUM_ALL_CHR: 25
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - OX442374.1
        - OX442375.1
        - OX442376.1
        - OX442377.1
        - OX442378.1
        - OX442379.1
        - OX442380.1
        - OX442381.1
        - OX442382.1
        - OX442383.1
        - OX442384.1
        - OX442385.1
        - OX442386.1
        - OX442387.1
        - OX442388.1
        - OX442389.1
        - OX442390.1
        - OX442391.1
        - OX442392.1
        - OX442393.1
        - OX442394.1
        - OX442395.1
        - OX442396.1
        - OX442397.1
        - OX442398.1 
    AUTOSOMAL_CHROMOSOMES: 
        - OX442374.1
        - OX442375.1
        - OX442376.1
        - OX442377.1
        - OX442378.1
        - OX442379.1
        - OX442380.1
        - OX442381.1
        - OX442382.1
        - OX442383.1
        - OX442384.1
        - OX442385.1
        - OX442386.1
        - OX442387.1
        - OX442388.1
        - OX442389.1
        - OX442390.1
        - OX442391.1
        - OX442392.1
        - OX442393.1
        - OX442394.1
        - OX442395.1
        - OX442396.1
        - OX442397.1
        - OX442398.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
