    CLADE : fishes 
    SPEC_NAME : GouWil 
    FULL_SPEC_NAME : Gouania_willdenowi 
    ALN_NAME : fGouWil 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 23
    NUM_ALL_CHR: 23
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_041044.1
        - NC_041045.1
        - NC_041046.1
        - NC_041047.1
        - NC_041048.1
        - NC_041049.1
        - NC_041050.1
        - NC_041051.1
        - NC_041052.1
        - NC_041053.1
        - NC_041054.1
        - NC_041055.1
        - NC_041056.1
        - NC_041057.1
        - NC_041058.1
        - NC_041059.1
        - NC_041060.1
        - NC_041061.1
        - NC_041062.1
        - NC_041063.1
        - NC_041064.1
        - NC_041065.1
        - NC_041066.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_041044.1
        - NC_041045.1
        - NC_041046.1
        - NC_041047.1
        - NC_041048.1
        - NC_041049.1
        - NC_041050.1
        - NC_041051.1
        - NC_041052.1
        - NC_041053.1
        - NC_041054.1
        - NC_041055.1
        - NC_041056.1
        - NC_041057.1
        - NC_041058.1
        - NC_041059.1
        - NC_041060.1
        - NC_041061.1
        - NC_041062.1
        - NC_041063.1
        - NC_041064.1
        - NC_041065.1
        - NC_041066.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
