    CLADE : fishes 
    SPEC_NAME : LabBer 
    FULL_SPEC_NAME : Labrus_bergylta 
    ALN_NAME : fLabBer 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 24
    NUM_ALL_CHR: 24
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_089195.1
        - NC_089196.1
        - NC_089197.1
        - NC_089198.1
        - NC_089199.1
        - NC_089200.1
        - NC_089201.1
        - NC_089202.1
        - NC_089203.1
        - NC_089204.1
        - NC_089205.1
        - NC_089206.1
        - NC_089207.1
        - NC_089208.1
        - NC_089209.1
        - NC_089210.1
        - NC_089211.1
        - NC_089212.1
        - NC_089213.1
        - NC_089214.1
        - NC_089215.1
        - NC_089216.1
        - NC_089217.1
        - NC_089218.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_089195.1
        - NC_089196.1
        - NC_089197.1
        - NC_089198.1
        - NC_089199.1
        - NC_089200.1
        - NC_089201.1
        - NC_089202.1
        - NC_089203.1
        - NC_089204.1
        - NC_089205.1
        - NC_089206.1
        - NC_089207.1
        - NC_089208.1
        - NC_089209.1
        - NC_089210.1
        - NC_089211.1
        - NC_089212.1
        - NC_089213.1
        - NC_089214.1
        - NC_089215.1
        - NC_089216.1
        - NC_089217.1
        - NC_089218.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
