    CLADE : fishes 
    SPEC_NAME : LepOcu 
    FULL_SPEC_NAME : Lepisosteus_oculatus 
    ALN_NAME : fLepOcu 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 29
    NUM_ALL_CHR: 29
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_090696.1
        - NC_090697.1
        - NC_090698.1
        - NC_090699.1
        - NC_090700.1
        - NC_090701.1
        - NC_090702.1
        - NC_090703.1
        - NC_090704.1
        - NC_090705.1
        - NC_090706.1
        - NC_090707.1
        - NC_090708.1
        - NC_090709.1
        - NC_090710.1
        - NC_090711.1
        - NC_090712.1
        - NC_090713.1
        - NC_090714.1
        - NC_090715.1
        - NC_090716.1
        - NC_090717.1
        - NC_090718.1
        - NC_090719.1
        - NC_090720.1
        - NC_090721.1
        - NC_090722.1
        - NC_090723.1
        - NC_090724.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_090696.1
        - NC_090697.1
        - NC_090698.1
        - NC_090699.1
        - NC_090700.1
        - NC_090701.1
        - NC_090702.1
        - NC_090703.1
        - NC_090704.1
        - NC_090705.1
        - NC_090706.1
        - NC_090707.1
        - NC_090708.1
        - NC_090709.1
        - NC_090710.1
        - NC_090711.1
        - NC_090712.1
        - NC_090713.1
        - NC_090714.1
        - NC_090715.1
        - NC_090716.1
        - NC_090717.1
        - NC_090718.1
        - NC_090719.1
        - NC_090720.1
        - NC_090721.1
        - NC_090722.1
        - NC_090723.1
        - NC_090724.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
