    CLADE : fishes 
    SPEC_NAME : MegCyp 
    FULL_SPEC_NAME : Megalops_cyprinoides 
    ALN_NAME : fMegCyp 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 25
    NUM_ALL_CHR: 25
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_050583.1
        - NC_050584.1
        - NC_050585.1
        - NC_050586.1
        - NC_050587.1
        - NC_050588.1
        - NC_050589.1
        - NC_050590.1
        - NC_050591.1
        - NC_050592.1
        - NC_050593.1
        - NC_050594.1
        - NC_050595.1
        - NC_050596.1
        - NC_050597.1
        - NC_050598.1
        - NC_050599.1
        - NC_050600.1
        - NC_050601.1
        - NC_050602.1
        - NC_050603.1
        - NC_050604.1
        - NC_050605.1
        - NC_050606.1
        - NC_050607.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_050583.1
        - NC_050584.1
        - NC_050585.1
        - NC_050586.1
        - NC_050587.1
        - NC_050588.1
        - NC_050589.1
        - NC_050590.1
        - NC_050591.1
        - NC_050592.1
        - NC_050593.1
        - NC_050594.1
        - NC_050595.1
        - NC_050596.1
        - NC_050597.1
        - NC_050598.1
        - NC_050599.1
        - NC_050600.1
        - NC_050601.1
        - NC_050602.1
        - NC_050603.1
        - NC_050604.1
        - NC_050605.1
        - NC_050606.1
        - NC_050607.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
