    CLADE : fishes 
    SPEC_NAME : NeoGra 
    FULL_SPEC_NAME : Neoarius_graeffei 
    ALN_NAME : fNeoGra 
    CHROM_START_CHR : NC    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 28 
    NUM_ALL_CHR: 28
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_083569.1
        - NC_083570.1
        - NC_083571.1
        - NC_083572.1
        - NC_083573.1
        - NC_083574.1
        - NC_083575.1
        - NC_083576.1
        - NC_083577.1
        - NC_083578.1
        - NC_083579.1
        - NC_083580.1
        - NC_083581.1
        - NC_083582.1
        - NC_083583.1
        - NC_083584.1
        - NC_083585.1
        - NC_083586.1
        - NC_083587.1
        - NC_083588.1
        - NC_083589.1
        - NC_083590.1
        - NC_083591.1
        - NC_083592.1
        - NC_083593.1
        - NC_083594.1
        - NC_083595.1
        - NC_083596.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_083569.1
        - NC_083570.1
        - NC_083571.1
        - NC_083572.1
        - NC_083573.1
        - NC_083574.1
        - NC_083575.1
        - NC_083576.1
        - NC_083577.1
        - NC_083578.1
        - NC_083579.1
        - NC_083580.1
        - NC_083581.1
        - NC_083582.1
        - NC_083583.1
        - NC_083584.1
        - NC_083585.1
        - NC_083586.1
        - NC_083587.1
        - NC_083588.1
        - NC_083589.1
        - NC_083590.1
        - NC_083591.1
        - NC_083592.1
        - NC_083593.1
        - NC_083594.1
        - NC_083595.1
        - NC_083596.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
