    CLADE : fishes
    SPEC_NAME : NeoOce 
    FULL_SPEC_NAME : Neosynchiropus_ocellatus  
    ALN_NAME : fNeoOce
    CHROM_START_CHR : CM
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 20
    NUM_ALL_CHR: 20
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM094609.1
        - CM094610.1
        - CM094611.1
        - CM094612.1
        - CM094613.1
        - CM094614.1
        - CM094615.1
        - CM094616.1
        - CM094617.1
        - CM094618.1
        - CM094619.1
        - CM094620.1
        - CM094621.1
        - CM094622.1
        - CM094623.1
        - CM094624.1
        - CM094625.1
        - CM094626.1
        - CM094627.1
        - CM094628.1
    AUTOSOMAL_CHROMOSOMES: 
        - CM094609.1
        - CM094610.1
        - CM094611.1
        - CM094612.1
        - CM094613.1
        - CM094614.1
        - CM094615.1
        - CM094616.1
        - CM094617.1
        - CM094618.1
        - CM094619.1
        - CM094620.1
        - CM094621.1
        - CM094622.1
        - CM094623.1
        - CM094624.1
        - CM094625.1
        - CM094626.1
        - CM094627.1
        - CM094628.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
