    CLADE : fishes 
    SPEC_NAME : OsmEpe 
    FULL_SPEC_NAME : Osmerus_eperlanus 
    ALN_NAME : fOsmEpe 
    CHROM_START_CHR : NC    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 28
    NUM_ALL_CHR: 28
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_085018.1
        - NC_085019.1
        - NC_085020.1
        - NC_085021.1
        - NC_085022.1
        - NC_085023.1
        - NC_085024.1
        - NC_085025.1
        - NC_085026.1
        - NC_085027.1
        - NC_085028.1
        - NC_085029.1
        - NC_085030.1
        - NC_085031.1
        - NC_085032.1
        - NC_085033.1
        - NC_085034.1
        - NC_085035.1
        - NC_085036.1
        - NC_085037.1
        - NC_085038.1
        - NC_085039.1
        - NC_085040.1
        - NC_085041.1
        - NC_085042.1
        - NC_085043.1
        - NC_085044.1
        - NC_085045.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_085018.1
        - NC_085019.1
        - NC_085020.1
        - NC_085021.1
        - NC_085022.1
        - NC_085023.1
        - NC_085024.1
        - NC_085025.1
        - NC_085026.1
        - NC_085027.1
        - NC_085028.1
        - NC_085029.1
        - NC_085030.1
        - NC_085031.1
        - NC_085032.1
        - NC_085033.1
        - NC_085034.1
        - NC_085035.1
        - NC_085036.1
        - NC_085037.1
        - NC_085038.1
        - NC_085039.1
        - NC_085040.1
        - NC_085041.1
        - NC_085042.1
        - NC_085043.1
        - NC_085044.1
        - NC_085045.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
