    CLADE : fishes 
    SPEC_NAME : PanHyp 
    FULL_SPEC_NAME : Pangasianodon_hypophthalmus 
    ALN_NAME : fPanHyp 
    CHROM_START_CHR : NC    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 30
    NUM_ALL_CHR: 30
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_069710.1
        - NC_069711.1
        - NC_069712.1
        - NC_069713.1
        - NC_069714.1
        - NC_069715.1
        - NC_069716.1
        - NC_069717.1
        - NC_069718.1
        - NC_069719.1
        - NC_069720.1
        - NC_069721.1
        - NC_069722.1
        - NC_069723.1
        - NC_069724.1
        - NC_069725.1
        - NC_069726.1
        - NC_069727.1
        - NC_069728.1
        - NC_069729.1
        - NC_069730.1
        - NC_069731.1
        - NC_069732.1
        - NC_069733.1
        - NC_069734.1
        - NC_069735.1
        - NC_069736.1
        - NC_069737.1
        - NC_069738.1
        - NC_069739.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_069710.1
        - NC_069711.1
        - NC_069712.1
        - NC_069713.1
        - NC_069714.1
        - NC_069715.1
        - NC_069716.1
        - NC_069717.1
        - NC_069718.1
        - NC_069719.1
        - NC_069720.1
        - NC_069721.1
        - NC_069722.1
        - NC_069723.1
        - NC_069724.1
        - NC_069725.1
        - NC_069726.1
        - NC_069727.1
        - NC_069728.1
        - NC_069729.1
        - NC_069730.1
        - NC_069731.1
        - NC_069732.1
        - NC_069733.1
        - NC_069734.1
        - NC_069735.1
        - NC_069736.1
        - NC_069737.1
        - NC_069738.1
        - NC_069739.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
