    CLADE : fishes 
    SPEC_NAME : PolPol 
    FULL_SPEC_NAME : Pollachius_pollachius 
    ALN_NAME : fPolPol 
    CHROM_START_CHR : OX    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 20
    NUM_ALL_CHR: 20
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - OX465124.1
        - OX465125.1
        - OX465126.1
        - OX465127.1
        - OX465128.1
        - OX465129.1
        - OX465130.1
        - OX465131.1
        - OX465132.1
        - OX465133.1
        - OX465134.1
        - OX465135.1
        - OX465136.1
        - OX465137.1
        - OX465138.1
        - OX465139.1
        - OX465140.1
        - OX465141.1
        - OX465142.1
        - OX465143.1
    AUTOSOMAL_CHROMOSOMES: 
        - OX465124.1
        - OX465125.1
        - OX465126.1
        - OX465127.1
        - OX465128.1
        - OX465129.1
        - OX465130.1
        - OX465131.1
        - OX465132.1
        - OX465133.1
        - OX465134.1
        - OX465135.1
        - OX465136.1
        - OX465137.1
        - OX465138.1
        - OX465139.1
        - OX465140.1
        - OX465141.1
        - OX465142.1
        - OX465143.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
