    CLADE : fishes 
    SPEC_NAME : PygNat 
    FULL_SPEC_NAME : Pygocentrus_nattereri 
    ALN_NAME : fPygNat 
    CHROM_START_CHR : NC    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 30
    NUM_ALL_CHR: 30
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_051211.1
        - NC_051212.1
        - NC_051213.1
        - NC_051214.1
        - NC_051215.1
        - NC_051216.1
        - NC_051217.1
        - NC_051218.1
        - NC_051219.1
        - NC_051220.1
        - NC_051221.1
        - NC_051222.1
        - NC_051223.1
        - NC_051224.1
        - NC_051225.1
        - NC_051226.1
        - NC_051227.1
        - NC_051228.1
        - NC_051229.1
        - NC_051230.1
        - NC_051231.1
        - NC_051232.1
        - NC_051233.1
        - NC_051234.1
        - NC_051235.1
        - NC_051236.1
        - NC_051237.1
        - NC_051238.1
        - NC_051239.1
        - NC_051240.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_051211.1
        - NC_051212.1
        - NC_051213.1
        - NC_051214.1
        - NC_051215.1
        - NC_051216.1
        - NC_051217.1
        - NC_051218.1
        - NC_051219.1
        - NC_051220.1
        - NC_051221.1
        - NC_051222.1
        - NC_051223.1
        - NC_051224.1
        - NC_051225.1
        - NC_051226.1
        - NC_051227.1
        - NC_051228.1
        - NC_051229.1
        - NC_051230.1
        - NC_051231.1
        - NC_051232.1
        - NC_051233.1
        - NC_051234.1
        - NC_051235.1
        - NC_051236.1
        - NC_051237.1
        - NC_051238.1
        - NC_051239.1
        - NC_051240.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
