    CLADE : fishes 
    SPEC_NAME : SalFas 
    FULL_SPEC_NAME : Salarias_fasciatus 
    ALN_NAME : fSalFas 
    CHROM_START_CHR : NC    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 22
    NUM_ALL_CHR: 22
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_043745.1
        - NC_043746.1
        - NC_043747.1
        - NC_043748.1
        - NC_043749.1
        - NC_043750.1
        - NC_043751.1
        - NC_043752.1
        - NC_043753.1
        - NC_043754.1
        - NC_043755.1
        - NC_043756.1
        - NC_043757.1
        - NC_043758.1
        - NC_043759.1
        - NC_043760.1
        - NC_043761.1
        - NC_043762.1
        - NC_043763.1
        - NC_043764.1
        - NC_043765.1
        - NC_043766.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_043745.1
        - NC_043746.1
        - NC_043747.1
        - NC_043748.1
        - NC_043749.1
        - NC_043750.1
        - NC_043751.1
        - NC_043752.1
        - NC_043753.1
        - NC_043754.1
        - NC_043755.1
        - NC_043756.1
        - NC_043757.1
        - NC_043758.1
        - NC_043759.1
        - NC_043760.1
        - NC_043761.1
        - NC_043762.1
        - NC_043763.1
        - NC_043764.1
        - NC_043765.1
        - NC_043766.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
