    CLADE : fishes 
    SPEC_NAME : ScaEry 
    FULL_SPEC_NAME : Scardinius_erythrophthalmus
    ALN_NAME : fScaEry
    CHROM_START_CHR : OZ
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 25
    NUM_ALL_CHR: 25
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - OZ078834.1
        - OZ078835.1
        - OZ078836.1
        - OZ078837.1
        - OZ078838.1
        - OZ078839.1
        - OZ078840.1
        - OZ078841.1
        - OZ078842.1
        - OZ078843.1
        - OZ078844.1
        - OZ078845.1
        - OZ078846.1
        - OZ078847.1
        - OZ078848.1
        - OZ078849.1
        - OZ078850.1
        - OZ078851.1
        - OZ078852.1
        - OZ078853.1
        - OZ078854.1
        - OZ078855.1
        - OZ078856.1
        - OZ078857.1
        - OZ078858.1 
    AUTOSOMAL_CHROMOSOMES: 
        - OZ078834.1
        - OZ078835.1
        - OZ078836.1
        - OZ078837.1
        - OZ078838.1
        - OZ078839.1
        - OZ078840.1
        - OZ078841.1
        - OZ078842.1
        - OZ078843.1
        - OZ078844.1
        - OZ078845.1
        - OZ078846.1
        - OZ078847.1
        - OZ078848.1
        - OZ078849.1
        - OZ078850.1
        - OZ078851.1
        - OZ078852.1
        - OZ078853.1
        - OZ078854.1
        - OZ078855.1
        - OZ078856.1
        - OZ078857.1
        - OZ078858.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
