    CLADE : fishes 
    SPEC_NAME : SebFas 
    FULL_SPEC_NAME : Sebastes_fasciatus 
    ALN_NAME : fSebFas 
    CHROM_START_CHR : CM    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 24
    NUM_ALL_CHR: 24
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM091681.1
        - CM091682.1
        - CM091683.1
        - CM091684.1
        - CM091685.1
        - CM091686.1
        - CM091687.1
        - CM091688.1
        - CM091689.1
        - CM091690.1
        - CM091691.1
        - CM091692.1
        - CM091693.1
        - CM091694.1
        - CM091695.1
        - CM091696.1
        - CM091697.1
        - CM091698.1
        - CM091699.1
        - CM091700.1
        - CM091701.1
        - CM091702.1
        - CM091703.1
        - CM091704.1
    AUTOSOMAL_CHROMOSOMES: 
        - CM091681.1
        - CM091682.1
        - CM091683.1
        - CM091684.1
        - CM091685.1
        - CM091686.1
        - CM091687.1
        - CM091688.1
        - CM091689.1
        - CM091690.1
        - CM091691.1
        - CM091692.1
        - CM091693.1
        - CM091694.1
        - CM091695.1
        - CM091696.1
        - CM091697.1
        - CM091698.1
        - CM091699.1
        - CM091700.1
        - CM091701.1
        - CM091702.1
        - CM091703.1
        - CM091704.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
