    CLADE : fishes 
    SPEC_NAME : ThuMac 
    FULL_SPEC_NAME : Thunnus_maccoyii 
    ALN_NAME : fThuMac 
    CHROM_START_CHR : NC    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 24
    NUM_ALL_CHR: 24
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_056533.1
        - NC_056534.1
        - NC_056535.1
        - NC_056536.1
        - NC_056537.1
        - NC_056538.1
        - NC_056539.1
        - NC_056540.1
        - NC_056541.1
        - NC_056542.1
        - NC_056543.1
        - NC_056544.1
        - NC_056545.1
        - NC_056546.1
        - NC_056547.1
        - NC_056548.1
        - NC_056549.1
        - NC_056550.1
        - NC_056551.1
        - NC_056552.1
        - NC_056553.1
        - NC_056554.1
        - NC_056555.1
        - NC_056556.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_056533.1
        - NC_056534.1
        - NC_056535.1
        - NC_056536.1
        - NC_056537.1
        - NC_056538.1
        - NC_056539.1
        - NC_056540.1
        - NC_056541.1
        - NC_056542.1
        - NC_056543.1
        - NC_056544.1
        - NC_056545.1
        - NC_056546.1
        - NC_056547.1
        - NC_056548.1
        - NC_056549.1
        - NC_056550.1
        - NC_056551.1
        - NC_056552.1
        - NC_056553.1
        - NC_056554.1
        - NC_056555.1
        - NC_056556.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
