    CLADE : fishes 
    SPEC_NAME : ThuThy 
    FULL_SPEC_NAME : Thunnus_thynnus 
    ALN_NAME : fThuThy 
    CHROM_START_CHR : NC    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 24
    NUM_ALL_CHR: 24
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_089517.1
        - NC_089518.1
        - NC_089519.1
        - NC_089520.1
        - NC_089521.1
        - NC_089522.1
        - NC_089523.1
        - NC_089524.1
        - NC_089525.1
        - NC_089526.1
        - NC_089527.1
        - NC_089528.1
        - NC_089529.1
        - NC_089530.1
        - NC_089531.1
        - NC_089532.1
        - NC_089533.1
        - NC_089534.1
        - NC_089535.1
        - NC_089536.1
        - NC_089537.1
        - NC_089538.1
        - NC_089539.1
        - NC_089540.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_089517.1
        - NC_089518.1
        - NC_089519.1
        - NC_089520.1
        - NC_089521.1
        - NC_089522.1
        - NC_089523.1
        - NC_089524.1
        - NC_089525.1
        - NC_089526.1
        - NC_089527.1
        - NC_089528.1
        - NC_089529.1
        - NC_089530.1
        - NC_089531.1
        - NC_089532.1
        - NC_089533.1
        - NC_089534.1
        - NC_089535.1
        - NC_089536.1
        - NC_089537.1
        - NC_089538.1
        - NC_089539.1
        - NC_089540.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
