    CLADE : fishes 
    SPEC_NAME : TriRos 
    FULL_SPEC_NAME : Trichomycterus_rosablanca 
    ALN_NAME : fTriRos 
    CHROM_START_CHR : NC 
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 27 
    NUM_ALL_CHR: 27
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_085988.1
        - NC_085989.1
        - NC_085990.1
        - NC_085991.1
        - NC_085992.1
        - NC_085993.1
        - NC_085994.1
        - NC_085995.1
        - NC_085996.1
        - NC_085997.1
        - NC_085998.1
        - NC_085999.1
        - NC_086000.1
        - NC_086001.1
        - NC_086002.1
        - NC_086003.1
        - NC_086004.1
        - NC_086005.1
        - NC_086006.1
        - NC_086007.1
        - NC_086008.1
        - NC_086009.1
        - NC_086010.1
        - NC_086011.1
        - NC_086012.1
        - NC_086013.1
        - NC_086014.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_085988.1
        - NC_085989.1
        - NC_085990.1
        - NC_085991.1
        - NC_085992.1
        - NC_085993.1
        - NC_085994.1
        - NC_085995.1
        - NC_085996.1
        - NC_085997.1
        - NC_085998.1
        - NC_085999.1
        - NC_086000.1
        - NC_086001.1
        - NC_086002.1
        - NC_086003.1
        - NC_086004.1
        - NC_086005.1
        - NC_086006.1
        - NC_086007.1
        - NC_086008.1
        - NC_086009.1
        - NC_086010.1
        - NC_086011.1
        - NC_086012.1
        - NC_086013.1
        - NC_086014.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
