    CLADE : chordates 
    SPEC_NAME : ClaLep 
    FULL_SPEC_NAME : Clavelina_lepadiformis 
    ALN_NAME : kClaLep 
    CHROM_START_CHR : OX
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 9
    NUM_ALL_CHR: 9
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - OX392439.1
        - OX392440.1
        - OX392441.1
        - OX392442.1
        - OX392443.1
        - OX392444.1
        - OX392445.1
        - OX392446.1
        - OX392447.1 
    AUTOSOMAL_CHROMOSOMES: 
        - OX392439.1
        - OX392440.1
        - OX392441.1
        - OX392442.1
        - OX392443.1
        - OX392444.1
        - OX392445.1
        - OX392446.1
        - OX392447.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
