    CLADE : sharks 
    SPEC_NAME : CarCar 
    FULL_SPEC_NAME : Carcharodon_carcharias 
    ALN_NAME : sCarCar 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 40
    NUM_ALL_CHR: 42
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 53
    ALL_CHROMOSOMES : 
        - NC_054467.1
        - NC_054468.1
        - NC_054469.1
        - NC_054470.1
        - NC_054471.1
        - NC_054472.1
        - NC_054473.1
        - NC_054474.1
        - NC_054475.1
        - NC_054476.1
        - NC_054477.1
        - NC_054478.1
        - NC_054479.1
        - NC_054480.1
        - NC_054481.1
        - NC_054482.1
        - NC_054483.1
        - NC_054484.1
        - NC_054485.1
        - NC_054486.1
        - NC_054487.1
        - NC_054488.1
        - NC_054489.1
        - NC_054490.1
        - NC_054491.1
        - NC_054492.1
        - NC_054493.1
        - NC_054494.1
        - NC_054495.1
        - NC_054496.1
        - NC_054497.1
        - NC_054498.1
        - NC_054499.1
        - NC_054500.1
        - NC_054501.1
        - NC_054502.1
        - NC_054503.1
        - NC_054504.1
        - NC_054505.1
        - NC_054506.1
        - NC_054507.1
        - NC_054508.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_054467.1
        - NC_054468.1
        - NC_054469.1
        - NC_054470.1
        - NC_054471.1
        - NC_054472.1
        - NC_054473.1
        - NC_054474.1
        - NC_054475.1
        - NC_054476.1
        - NC_054477.1
        - NC_054478.1
        - NC_054479.1
        - NC_054480.1
        - NC_054481.1
        - NC_054482.1
        - NC_054483.1
        - NC_054484.1
        - NC_054485.1
        - NC_054486.1
        - NC_054487.1
        - NC_054488.1
        - NC_054489.1
        - NC_054490.1
        - NC_054491.1
        - NC_054492.1
        - NC_054493.1
        - NC_054494.1
        - NC_054495.1
        - NC_054496.1
        - NC_054497.1
        - NC_054498.1
        - NC_054499.1
        - NC_054500.1
        - NC_054501.1
        - NC_054502.1
        - NC_054503.1
        - NC_054504.1
        - NC_054505.1
        - NC_054506.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
