    CLADE : "sharks"
    SPEC_NAME : "HypSab"
    FULL_SPEC_NAME : "Hypanus_sabinus"
    ALN_NAME : "sHypSab"
    REF_NAME : "GCF_030144855.1"
    ALT_NAME : "GCA_030144785.1"
    CHROM_START_CHR : "NC"
    WINDOW_INTERVAL : 500000
    WINDOW_LENGTH : 1000000
    NUM_AUT_CHROMOSOMES : 32
    NUM_ALL_CHR: 35
    MUTATION_RATE: 1.25e-8
    GENERATION_TIME: 18.8
    ALL_CHROMOSOMES : 
        - NC_082706.1
        - NC_082707.1
        - NC_082708.1
        - NC_082709.1
        - NC_082710.1
        - NC_082711.1
        - NC_082712.1
        - NC_082713.1
        - NC_082714.1
        - NC_082715.1
        - NC_082716.1
        - NC_082717.1
        - NC_082718.1
        - NC_082719.1
        - NC_082720.1
        - NC_082721.1
        - NC_082722.1
        - NC_082723.1
        - NC_082724.1
        - NC_082725.1
        - NC_082726.1
        - NC_082727.1
        - NC_082728.1
        - NC_082729.1
        - NC_082730.1
        - NC_082731.1
        - NC_082732.1
        - NC_082733.1
        - NC_082734.1
        - NC_082735.1
        - NC_082736.1
        - NC_082737.1
        - NC_082738.1
        - NC_082739.1
        - NC_082740.1
    AUTOSOMAL_CHROMOSOMES:
        - NC_082706.1
        - NC_082707.1
        - NC_082708.1
        - NC_082709.1
        - NC_082710.1
        - NC_082711.1
        - NC_082712.1
        - NC_082713.1
        - NC_082714.1
        - NC_082715.1
        - NC_082716.1
        - NC_082717.1
        - NC_082718.1
        - NC_082719.1
        - NC_082720.1
        - NC_082721.1
        - NC_082722.1
        - NC_082723.1
        - NC_082724.1
        - NC_082725.1
        - NC_082726.1
        - NC_082727.1
        - NC_082728.1
        - NC_082729.1
        - NC_082730.1
        - NC_082731.1
        - NC_082732.1
        - NC_082733.1
        - NC_082734.1
        - NC_082735.1
        - NC_082736.1
        - NC_082737.1
    BOOTSTRAPPING_VALUES:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29

