    CLADE : "sharks"
    SPEC_NAME : "MobBir"
    FULL_SPEC_NAME : "Mobula_birostris"
    ALN_NAME : "sMobBir"
    REF_NAME : "GCA_030028105.1"
    ALT_NAME : "GCA_030035685.1"
    CHROM_START_CHR : "NC"
    WINDOW_INTERVAL : 500000
    WINDOW_LENGTH : 1000000
    NUM_AUT_CHROMOSOMES : 32
    NUM_ALL_CHR: 33
    MUTATION_RATE: 1.25e-8
    GENERATION_TIME: 29
    ALL_CHROMOSOMES : 
        - NC_092370.1
        - NC_092371.1
        - NC_092372.1
        - NC_092373.1
        - NC_092374.1
        - NC_092375.1
        - NC_092376.1
        - NC_092377.1
        - NC_092378.1
        - NC_092379.1
        - NC_092380.1
        - NC_092381.1
        - NC_092382.1
        - NC_092383.1
        - NC_092384.1
        - NC_092385.1
        - NC_092386.1
        - NC_092387.1
        - NC_092388.1
        - NC_092389.1
        - NC_092390.1
        - NC_092391.1
        - NC_092392.1
        - NC_092393.1
        - NC_092394.1
        - NC_092395.1
        - NC_092396.1
        - NC_092397.1
        - NC_092398.1
        - NC_092399.1
        - NC_092400.1
        - NC_092401.1
        - NC_092402.1
    AUTOSOMAL_CHROMOSOMES:
        - NC_092370.1
        - NC_092371.1
        - NC_092372.1
        - NC_092373.1
        - NC_092374.1
        - NC_092375.1
        - NC_092376.1
        - NC_092377.1
        - NC_092378.1
        - NC_092379.1
        - NC_092380.1
        - NC_092381.1
        - NC_092382.1
        - NC_092383.1
        - NC_092384.1
        - NC_092385.1
        - NC_092386.1
        - NC_092387.1
        - NC_092388.1
        - NC_092389.1
        - NC_092390.1
        - NC_092391.1
        - NC_092392.1
        - NC_092393.1
        - NC_092394.1
        - NC_092395.1
        - NC_092396.1
        - NC_092397.1
        - NC_092398.1
        - NC_092399.1
        - NC_092400.1
        - NC_092401.1
    BOOTSTRAPPING_VALUES :
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
