    CLADE : sharks 
    SPEC_NAME : MusAst 
    FULL_SPEC_NAME : Mustelus_asterias 
    ALN_NAME : sMusAst 
    CHROM_START_CHR : OZ    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 33
    NUM_ALL_CHR: 34
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - OZ172890.1
        - OZ172891.1
        - OZ172892.1
        - OZ172893.1
        - OZ172894.1
        - OZ172895.1
        - OZ172896.1
        - OZ172897.1
        - OZ172898.1
        - OZ172899.1
        - OZ172900.1
        - OZ172901.1
        - OZ172902.1
        - OZ172903.1
        - OZ172904.1
        - OZ172905.1
        - OZ172906.1
        - OZ172907.1
        - OZ172908.1
        - OZ172909.1
        - OZ172910.1
        - OZ172911.1
        - OZ172912.1
        - OZ172913.1
        - OZ172914.1
        - OZ172915.1
        - OZ172916.1
        - OZ172917.1
        - OZ172918.1
        - OZ172919.1
        - OZ172921.1
        - OZ172922.1
        - OZ172923.1 
        - OZ172920.1
    AUTOSOMAL_CHROMOSOMES: 
        - OZ172890.1
        - OZ172891.1
        - OZ172892.1
        - OZ172893.1
        - OZ172894.1
        - OZ172895.1
        - OZ172896.1
        - OZ172897.1
        - OZ172898.1
        - OZ172899.1
        - OZ172900.1
        - OZ172901.1
        - OZ172902.1
        - OZ172903.1
        - OZ172904.1
        - OZ172905.1
        - OZ172906.1
        - OZ172907.1
        - OZ172908.1
        - OZ172909.1
        - OZ172910.1
        - OZ172911.1
        - OZ172912.1
        - OZ172913.1
        - OZ172914.1
        - OZ172915.1
        - OZ172916.1
        - OZ172917.1
        - OZ172918.1
        - OZ172919.1
        - OZ172921.1
        - OZ172922.1
        - OZ172923.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
