    CLADE : sharks 
    SPEC_NAME : PriJap 
    FULL_SPEC_NAME : Pristiophorus_japonicus 
    ALN_NAME : sPriJap 
    CHROM_START_CHR : NC    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 33
    NUM_ALL_CHR: 35
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_091977.1
        - NC_091978.1
        - NC_091979.1
        - NC_091980.1
        - NC_091981.1
        - NC_091982.1
        - NC_091983.1
        - NC_091984.1
        - NC_091985.1
        - NC_091986.1
        - NC_091987.1
        - NC_091988.1
        - NC_091989.1
        - NC_091990.1
        - NC_091991.1
        - NC_091992.1
        - NC_091993.1
        - NC_091994.1
        - NC_091995.1
        - NC_091996.1
        - NC_091997.1
        - NC_091998.1
        - NC_091999.1
        - NC_092000.1
        - NC_092001.1
        - NC_092002.1
        - NC_092003.1
        - NC_092004.1
        - NC_092005.1
        - NC_092006.1
        - NC_092007.1
        - NC_092008.1
        - NC_092009.1
        - NC_092010.1
        - NC_092011.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_091977.1
        - NC_091978.1
        - NC_091979.1
        - NC_091980.1
        - NC_091981.1
        - NC_091982.1
        - NC_091983.1
        - NC_091984.1
        - NC_091985.1
        - NC_091986.1
        - NC_091987.1
        - NC_091988.1
        - NC_091989.1
        - NC_091990.1
        - NC_091991.1
        - NC_091992.1
        - NC_091993.1
        - NC_091994.1
        - NC_091995.1
        - NC_091996.1
        - NC_091997.1
        - NC_091998.1
        - NC_091999.1
        - NC_092000.1
        - NC_092001.1
        - NC_092002.1
        - NC_092003.1
        - NC_092004.1
        - NC_092005.1
        - NC_092006.1
        - NC_092007.1
        - NC_092008.1
        - NC_092009.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
