    CLADE : reptiles 
    SPEC_NAME : AllMis 
    FULL_SPEC_NAME : Alligator_mississippiensis 
    ALN_NAME : rAllMis 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 16
    NUM_ALL_CHR: 16
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_081824.1
        - NC_081825.1
        - NC_081826.1
        - NC_081827.1
        - NC_081828.1
        - NC_081829.1
        - NC_081830.1
        - NC_081831.1
        - NC_081832.1
        - NC_081833.1
        - NC_081834.1
        - NC_081835.1
        - NC_081836.1
        - NC_081837.1
        - NC_081838.1
        - NC_081839.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_081824.1
        - NC_081825.1
        - NC_081826.1
        - NC_081827.1
        - NC_081828.1
        - NC_081829.1
        - NC_081830.1
        - NC_081831.1
        - NC_081832.1
        - NC_081833.1
        - NC_081834.1
        - NC_081835.1
        - NC_081836.1
        - NC_081837.1
        - NC_081838.1
        - NC_081839.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
