    CLADE : reptiles 
    SPEC_NAME : CheMyd 
    FULL_SPEC_NAME : Chelonia_mydas 
    ALN_NAME : rCheMyd 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 28
    NUM_ALL_CHR: 28
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_051245.2
        - NC_051246.2
        - NC_051250.2
        - NC_051251.2
        - NC_051252.2
        - NC_051253.2
        - NC_051254.2
        - NC_051257.2
        - NC_051258.2
        - NC_051259.2
        - NC_051260.2
        - NC_051261.2
        - NC_051262.2
        - NC_051263.2
        - NC_051264.2
        - NC_051268.2
        - NC_057849.1
        - NC_057850.1
        - NC_057851.1
        - NC_057852.1
        - NC_057853.1
        - NC_057854.1
        - NC_057855.1
        - NC_057856.1
        - NC_057857.1
        - NC_057858.1
        - NC_057859.1
        - NC_057860.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_051245.2
        - NC_051246.2
        - NC_051250.2
        - NC_051251.2
        - NC_051252.2
        - NC_051253.2
        - NC_051254.2
        - NC_051257.2
        - NC_051258.2
        - NC_051259.2
        - NC_051260.2
        - NC_051261.2
        - NC_051262.2
        - NC_051263.2
        - NC_051264.2
        - NC_051268.2
        - NC_057849.1
        - NC_057850.1
        - NC_057851.1
        - NC_057852.1
        - NC_057853.1
        - NC_057854.1
        - NC_057855.1
        - NC_057856.1
        - NC_057857.1
        - NC_057858.1
        - NC_057859.1
        - NC_057860.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
