    CLADE : reptiles 
    SPEC_NAME : DerCor 
    FULL_SPEC_NAME : Dermochelys_coriacea 
    ALN_NAME : rDerCor 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 28
    NUM_ALL_CHR: 28
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_050068.2
        - NC_050069.1
        - NC_050070.1
        - NC_050071.1
        - NC_050072.1
        - NC_050073.1
        - NC_050074.1
        - NC_050075.1
        - NC_050076.1
        - NC_050077.1
        - NC_050078.2
        - NC_050079.1
        - NC_050080.1
        - NC_050081.1
        - NC_050082.1
        - NC_050083.1
        - NC_050084.1
        - NC_050085.1
        - NC_050086.2
        - NC_050087.2
        - NC_050088.1
        - NC_050089.1
        - NC_050090.1
        - NC_050091.1
        - NC_050092.1
        - NC_050093.1
        - NC_050094.1
        - NC_050095.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_050068.2
        - NC_050069.1
        - NC_050070.1
        - NC_050071.1
        - NC_050072.1
        - NC_050073.1
        - NC_050074.1
        - NC_050075.1
        - NC_050076.1
        - NC_050077.1
        - NC_050078.2
        - NC_050079.1
        - NC_050080.1
        - NC_050081.1
        - NC_050082.1
        - NC_050083.1
        - NC_050084.1
        - NC_050085.1
        - NC_050086.2
        - NC_050087.2
        - NC_050088.1
        - NC_050089.1
        - NC_050090.1
        - NC_050091.1
        - NC_050092.1
        - NC_050093.1
        - NC_050094.1
        - NC_050095.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
