    CLADE : reptiles 
    SPEC_NAME : DibSmi 
    FULL_SPEC_NAME : Dibamus_smithi 
    ALN_NAME : rDibSmi 
    CHROM_START_CHR : CM
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 17
    NUM_ALL_CHR: 19
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM100509.1
        - CM100510.1
        - CM100511.1
        - CM100512.1
        - CM100513.1
        - CM100514.1
        - CM100515.1
        - CM100516.1
        - CM100517.1
        - CM100518.1
        - CM100519.1
        - CM100520.1
        - CM100521.1
        - CM100522.1
        - CM100523.1
        - CM100524.1
        - CM100525.1
        - CM100526.1
        - CM100527.1
    AUTOSOMAL_CHROMOSOMES: 
        - CM100509.1
        - CM100510.1
        - CM100511.1
        - CM100512.1
        - CM100513.1
        - CM100514.1
        - CM100515.1
        - CM100516.1
        - CM100517.1
        - CM100518.1
        - CM100519.1
        - CM100520.1
        - CM100521.1
        - CM100522.1
        - CM100523.1
        - CM100524.1
        - CM100525.1
        - CM100526.1
        - CM100527.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
