    CLADE : reptiles 
    SPEC_NAME : EmyOrb 
    FULL_SPEC_NAME : Emys_orbicularis 
    ALN_NAME : rEmyOrb 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 25
    NUM_ALL_CHR: 25
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_088683.1
        - NC_088684.1
        - NC_088685.1
        - NC_088686.1
        - NC_088687.1
        - NC_088688.1
        - NC_088689.1
        - NC_088690.1
        - NC_088691.1
        - NC_088692.1
        - NC_088693.1
        - NC_088694.1
        - NC_088695.1
        - NC_088696.1
        - NC_088697.1
        - NC_088698.1
        - NC_088699.1
        - NC_088700.1
        - NC_088701.1
        - NC_088702.1
        - NC_088703.1
        - NC_088704.1
        - NC_088705.1
        - NC_088706.1
        - NC_088707.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_088683.1
        - NC_088684.1
        - NC_088685.1
        - NC_088686.1
        - NC_088687.1
        - NC_088688.1
        - NC_088689.1
        - NC_088690.1
        - NC_088691.1
        - NC_088692.1
        - NC_088693.1
        - NC_088694.1
        - NC_088695.1
        - NC_088696.1
        - NC_088697.1
        - NC_088698.1
        - NC_088699.1
        - NC_088700.1
        - NC_088701.1
        - NC_088702.1
        - NC_088703.1
        - NC_088704.1
        - NC_088705.1
        - NC_088706.1
        - NC_088707.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
