    CLADE : reptiles 
    SPEC_NAME : EulEur 
    FULL_SPEC_NAME : Euleptes_europaea 
    ALN_NAME : rEulEur 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 21
    NUM_ALL_CHR: 21
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_079312.1
        - NC_079313.1
        - NC_079314.1
        - NC_079315.1
        - NC_079316.1
        - NC_079317.1
        - NC_079318.1
        - NC_079319.1
        - NC_079320.1
        - NC_079321.1
        - NC_079322.1
        - NC_079323.1
        - NC_079324.1
        - NC_079325.1
        - NC_079326.1
        - NC_079327.1
        - NC_079328.1
        - NC_079329.1
        - NC_079330.1
        - NC_079331.1
        - NC_079332.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_079312.1
        - NC_079313.1
        - NC_079314.1
        - NC_079315.1
        - NC_079316.1
        - NC_079317.1
        - NC_079318.1
        - NC_079319.1
        - NC_079320.1
        - NC_079321.1
        - NC_079322.1
        - NC_079323.1
        - NC_079324.1
        - NC_079325.1
        - NC_079326.1
        - NC_079327.1
        - NC_079328.1
        - NC_079329.1
        - NC_079330.1
        - NC_079331.1
        - NC_079332.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
