    CLADE : reptiles 
    SPEC_NAME : PodGai 
    FULL_SPEC_NAME : Podarcis_gaigeae 
    ALN_NAME : rPodGai 
    CHROM_START_CHR : OZ
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 18
    NUM_ALL_CHR: 20
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - OZ066914.1
        - OZ066915.1
        - OZ066916.1
        - OZ066917.1
        - OZ066918.1
        - OZ066919.1
        - OZ066920.1
        - OZ066921.1
        - OZ066922.1
        - OZ066923.1
        - OZ066924.1
        - OZ066925.1
        - OZ066926.1
        - OZ066927.1
        - OZ066929.1
        - OZ066930.1
        - OZ066931.1
        - OZ066933.1
        - OZ066932.1
        - OZ066928.1
    AUTOSOMAL_CHROMOSOMES: 
        - OZ066914.1
        - OZ066915.1
        - OZ066916.1
        - OZ066917.1
        - OZ066918.1
        - OZ066919.1
        - OZ066920.1
        - OZ066921.1
        - OZ066922.1
        - OZ066923.1
        - OZ066924.1
        - OZ066925.1
        - OZ066926.1
        - OZ066927.1
        - OZ066929.1
        - OZ066930.1
        - OZ066931.1
        - OZ066933.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
