    CLADE : reptiles 
    SPEC_NAME : PodRaf 
    FULL_SPEC_NAME : Podarcis_raffonei 
    ALN_NAME : rPodRaf 
    CHROM_START_CHR : NC    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 18
    NUM_ALL_CHR: 20
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_070602.1
        - NC_070603.1
        - NC_070604.1
        - NC_070605.1
        - NC_070606.1
        - NC_070607.1
        - NC_070608.1
        - NC_070609.1
        - NC_070610.1
        - NC_070611.1
        - NC_070612.1
        - NC_070613.1
        - NC_070614.1
        - NC_070615.1
        - NC_070616.1
        - NC_070617.1
        - NC_070618.1
        - NC_070619.1
        - NC_070620.1
        - NC_070621.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_070602.1
        - NC_070603.1
        - NC_070604.1
        - NC_070605.1
        - NC_070606.1
        - NC_070607.1
        - NC_070608.1
        - NC_070609.1
        - NC_070610.1
        - NC_070611.1
        - NC_070612.1
        - NC_070613.1
        - NC_070614.1
        - NC_070615.1
        - NC_070616.1
        - NC_070617.1
        - NC_070618.1
        - NC_070619.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
