    CLADE : reptiles 
    SPEC_NAME : ZooViv 
    FULL_SPEC_NAME : Zootoca_vivipara 
    ALN_NAME : rZooViv 
    CHROM_START_CHR : NC    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 17
    NUM_ALL_CHR: 19
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_083276.1
        - NC_083277.1
        - NC_083278.1
        - NC_083279.1
        - NC_083280.1
        - NC_083281.1
        - NC_083282.1
        - NC_083283.1
        - NC_083284.1
        - NC_083285.1
        - NC_083286.1
        - NC_083287.1
        - NC_083288.1
        - NC_083289.1
        - NC_083290.1
        - NC_083291.1
        - NC_083292.1
        - NC_083293.1
        - NC_083294.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_083276.1
        - NC_083277.1
        - NC_083278.1
        - NC_083279.1
        - NC_083280.1
        - NC_083281.1
        - NC_083282.1
        - NC_083283.1
        - NC_083284.1
        - NC_083285.1
        - NC_083286.1
        - NC_083287.1
        - NC_083288.1
        - NC_083289.1
        - NC_083290.1
        - NC_083291.1
        - NC_083292.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
