    CLADE : mammals 
    SPEC_NAME : ApoSyl 
    FULL_SPEC_NAME : Apodemus_sylvaticus 
    ALN_NAME : mApoSyl 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 23
    NUM_ALL_CHR: 25
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_067472.1
        - NC_067473.1
        - NC_067474.1
        - NC_067475.1
        - NC_067476.1
        - NC_067477.1
        - NC_067478.1
        - NC_067479.1
        - NC_067480.1
        - NC_067481.1
        - NC_067482.1
        - NC_067483.1
        - NC_067484.1
        - NC_067485.1
        - NC_067486.1
        - NC_067487.1
        - NC_067488.1
        - NC_067489.1
        - NC_067490.1
        - NC_067491.1
        - NC_067492.1
        - NC_067493.1
        - NC_067494.1
        - NC_067495.1
        - NC_067496.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_067472.1
        - NC_067473.1
        - NC_067474.1
        - NC_067475.1
        - NC_067476.1
        - NC_067477.1
        - NC_067478.1
        - NC_067479.1
        - NC_067480.1
        - NC_067481.1
        - NC_067482.1
        - NC_067483.1
        - NC_067484.1
        - NC_067485.1
        - NC_067486.1
        - NC_067487.1
        - NC_067488.1
        - NC_067489.1
        - NC_067490.1
        - NC_067491.1
        - NC_067492.1
        - NC_067493.1
        - NC_067494.1
        - NC_067495.1
        - NC_067496.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
