    CLADE : mammals 
    SPEC_NAME : BosTau 
    FULL_SPEC_NAME : Bos_taurus 
    ALN_NAME : mBosTau 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 29
    NUM_ALL_CHR: 30
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_040076.1
        - NC_040077.1
        - NC_040078.1
        - NC_040079.1
        - NC_040080.1
        - NC_040081.1
        - NC_040082.1
        - NC_040083.1
        - NC_040084.1
        - NC_040085.1
        - NC_040086.1
        - NC_040087.1
        - NC_040088.1
        - NC_040089.1
        - NC_040090.1
        - NC_040091.1
        - NC_040092.1
        - NC_040093.1
        - NC_040094.1
        - NC_040095.1
        - NC_040096.1
        - NC_040097.1
        - NC_040098.1
        - NC_040099.1
        - NC_040100.1
        - NC_040101.1
        - NC_040102.1
        - NC_040103.1
        - NC_040104.1
        - NC_040105.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_040076.1
        - NC_040077.1
        - NC_040078.1
        - NC_040079.1
        - NC_040080.1
        - NC_040081.1
        - NC_040082.1
        - NC_040083.1
        - NC_040084.1
        - NC_040085.1
        - NC_040086.1
        - NC_040087.1
        - NC_040088.1
        - NC_040089.1
        - NC_040090.1
        - NC_040091.1
        - NC_040092.1
        - NC_040093.1
        - NC_040094.1
        - NC_040095.1
        - NC_040096.1
        - NC_040097.1
        - NC_040098.1
        - NC_040099.1
        - NC_040100.1
        - NC_040101.1
        - NC_040102.1
        - NC_040103.1
        - NC_040104.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
