    CLADE : mammals 
    SPEC_NAME : CamDro 
    FULL_SPEC_NAME : Camelus_dromedarius  
    ALN_NAME : mCamDro 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 36
    NUM_ALL_CHR: 38
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_087436.1
        - NC_087437.1
        - NC_087438.1
        - NC_087439.1
        - NC_087440.1
        - NC_087441.1
        - NC_087442.1
        - NC_087443.1
        - NC_087444.1
        - NC_087445.1
        - NC_087446.1
        - NC_087447.1
        - NC_087448.1
        - NC_087449.1
        - NC_087450.1
        - NC_087451.1
        - NC_087452.1
        - NC_087453.1
        - NC_087454.1
        - NC_087455.1
        - NC_087456.1
        - NC_087457.1
        - NC_087458.1
        - NC_087459.1
        - NC_087460.1
        - NC_087461.1
        - NC_087462.1
        - NC_087463.1
        - NC_087464.1
        - NC_087465.1
        - NC_087466.1
        - NC_087467.1
        - NC_087468.1
        - NC_087469.1
        - NC_087470.1
        - NC_087471.1
        - NC_087472.1
        - NC_087473.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_087436.1
        - NC_087437.1
        - NC_087438.1
        - NC_087439.1
        - NC_087440.1
        - NC_087441.1
        - NC_087442.1
        - NC_087443.1
        - NC_087444.1
        - NC_087445.1
        - NC_087446.1
        - NC_087447.1
        - NC_087448.1
        - NC_087449.1
        - NC_087450.1
        - NC_087451.1
        - NC_087452.1
        - NC_087453.1
        - NC_087454.1
        - NC_087455.1
        - NC_087456.1
        - NC_087457.1
        - NC_087458.1
        - NC_087459.1
        - NC_087460.1
        - NC_087461.1
        - NC_087462.1
        - NC_087463.1
        - NC_087464.1
        - NC_087465.1
        - NC_087466.1
        - NC_087467.1
        - NC_087468.1
        - NC_087469.1
        - NC_087470.1
        - NC_087471.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
