    CLADE : mammals 
    SPEC_NAME : CanLup 
    FULL_SPEC_NAME : Canis_lupus 
    ALN_NAME : mCanLup
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 38
    NUM_ALL_CHR: 40
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_132838.1
        - NC_132839.1
        - NC_132840.1
        - NC_132841.1
        - NC_132842.1
        - NC_132843.1
        - NC_132844.1
        - NC_132845.1
        - NC_132846.1
        - NC_132847.1
        - NC_132848.1
        - NC_132849.1
        - NC_132850.1
        - NC_132851.1
        - NC_132852.1
        - NC_132853.1
        - NC_132854.1
        - NC_132855.1
        - NC_132856.1
        - NC_132857.1
        - NC_132858.1
        - NC_132859.1
        - NC_132860.1
        - NC_132861.1
        - NC_132862.1
        - NC_132863.1
        - NC_132864.1
        - NC_132865.1
        - NC_132866.1
        - NC_132867.1
        - NC_132868.1
        - NC_132869.1
        - NC_132870.1
        - NC_132871.1
        - NC_132872.1
        - NC_132873.1
        - NC_132874.1
        - NC_132875.1
        - NC_132876.1
        - NC_132877.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_132838.1
        - NC_132839.1
        - NC_132840.1
        - NC_132841.1
        - NC_132842.1
        - NC_132843.1
        - NC_132844.1
        - NC_132845.1
        - NC_132846.1
        - NC_132847.1
        - NC_132848.1
        - NC_132849.1
        - NC_132850.1
        - NC_132851.1
        - NC_132852.1
        - NC_132853.1
        - NC_132854.1
        - NC_132855.1
        - NC_132856.1
        - NC_132857.1
        - NC_132858.1
        - NC_132859.1
        - NC_132860.1
        - NC_132861.1
        - NC_132862.1
        - NC_132863.1
        - NC_132864.1
        - NC_132865.1
        - NC_132866.1
        - NC_132867.1
        - NC_132868.1
        - NC_132869.1
        - NC_132870.1
        - NC_132871.1
        - NC_132872.1
        - NC_132873.1
        - NC_132874.1
        - NC_132875.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
