    CLADE : mammals 
    SPEC_NAME : ChiNiv 
    FULL_SPEC_NAME : Chionomys_nivalis 
    ALN_NAME : mChiNiv 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 26
    NUM_ALL_CHR: 28
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_080086.1
        - NC_080087.1
        - NC_080088.1
        - NC_080089.1
        - NC_080090.1
        - NC_080091.1
        - NC_080092.1
        - NC_080093.1
        - NC_080094.1
        - NC_080095.1
        - NC_080096.1
        - NC_080097.1
        - NC_080098.1
        - NC_080099.1
        - NC_080100.1
        - NC_080101.1
        - NC_080102.1
        - NC_080103.1
        - NC_080104.1
        - NC_080105.1
        - NC_080106.1
        - NC_080107.1
        - NC_080108.1
        - NC_080109.1
        - NC_080110.1
        - NC_080111.1
        - NC_080112.1
        - NC_080113.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_080086.1
        - NC_080087.1
        - NC_080088.1
        - NC_080089.1
        - NC_080090.1
        - NC_080091.1
        - NC_080092.1
        - NC_080093.1
        - NC_080094.1
        - NC_080095.1
        - NC_080096.1
        - NC_080097.1
        - NC_080098.1
        - NC_080099.1
        - NC_080100.1
        - NC_080101.1
        - NC_080102.1
        - NC_080103.1
        - NC_080104.1
        - NC_080105.1
        - NC_080106.1
        - NC_080107.1
        - NC_080108.1
        - NC_080109.1
        - NC_080110.1
        - NC_080111.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
