    CLADE : mammals 
    SPEC_NAME : ChoDid 
    FULL_SPEC_NAME : Choloepus_didactylus 
    ALN_NAME : mChoDid 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 27
    NUM_ALL_CHR: 29
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_051307.1
        - NC_051308.1
        - NC_051309.1
        - NC_051310.1
        - NC_051311.1
        - NC_051312.1
        - NC_051313.1
        - NC_051314.1
        - NC_051315.1
        - NC_051316.1
        - NC_051317.1
        - NC_051318.1
        - NC_051319.1
        - NC_051320.1
        - NC_051321.1
        - NC_051322.1
        - NC_051323.1
        - NC_051324.1
        - NC_051325.1
        - NC_051326.1
        - NC_051327.1
        - NC_051328.1
        - NC_051329.1
        - NC_051330.1
        - NC_051331.1
        - NC_051332.1
        - NC_051333.1
        - NC_051334.1
        - NC_051335.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_051307.1
        - NC_051308.1
        - NC_051309.1
        - NC_051310.1
        - NC_051311.1
        - NC_051312.1
        - NC_051313.1
        - NC_051314.1
        - NC_051315.1
        - NC_051316.1
        - NC_051317.1
        - NC_051318.1
        - NC_051319.1
        - NC_051320.1
        - NC_051321.1
        - NC_051322.1
        - NC_051323.1
        - NC_051324.1
        - NC_051325.1
        - NC_051326.1
        - NC_051327.1
        - NC_051328.1
        - NC_051329.1
        - NC_051330.1
        - NC_051331.1
        - NC_051332.1
        - NC_051333.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
