    CLADE : mammals 
    SPEC_NAME : DamDam 
    FULL_SPEC_NAME : Dama_dama 
    ALN_NAME : mDamDam 
    CHROM_START_CHR : CM
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 33
    NUM_ALL_CHR: 34
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM106723.1
        - CM106724.1
        - CM106725.1
        - CM106726.1
        - CM106727.1
        - CM106728.1
        - CM106729.1
        - CM106730.1
        - CM106731.1
        - CM106732.1
        - CM106733.1
        - CM106734.1
        - CM106735.1
        - CM106736.1
        - CM106737.1
        - CM106738.1
        - CM106739.1
        - CM106740.1
        - CM106741.1
        - CM106742.1
        - CM106743.1
        - CM106744.1
        - CM106745.1
        - CM106746.1
        - CM106747.1
        - CM106748.1
        - CM106749.1
        - CM106750.1
        - CM106751.1
        - CM106752.1
        - CM106753.1
        - CM106754.1
        - CM106755.1
        - CM106756.1
    AUTOSOMAL_CHROMOSOMES: 
        - CM106723.1
        - CM106724.1
        - CM106725.1
        - CM106726.1
        - CM106727.1
        - CM106728.1
        - CM106729.1
        - CM106730.1
        - CM106731.1
        - CM106732.1
        - CM106733.1
        - CM106734.1
        - CM106735.1
        - CM106736.1
        - CM106737.1
        - CM106738.1
        - CM106739.1
        - CM106740.1
        - CM106741.1
        - CM106742.1
        - CM106743.1
        - CM106744.1
        - CM106745.1
        - CM106746.1
        - CM106747.1
        - CM106748.1
        - CM106749.1
        - CM106750.1
        - CM106751.1
        - CM106752.1
        - CM106753.1
        - CM106754.1
        - CM106755.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
