    CLADE : mammals 
    SPEC_NAME : DasMac 
    FULL_SPEC_NAME : Dasyurus_maculatus 
    ALN_NAME : mDasMac
    CHROM_START_CHR : CM
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 6
    NUM_ALL_CHR: 6
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM109194.1
        - CM109195.1
        - CM109196.1
        - CM109197.1
        - CM109198.1
        - CM109199.1
    AUTOSOMAL_CHROMOSOMES: 
        - CM109194.1
        - CM109195.1
        - CM109196.1
        - CM109197.1
        - CM109198.1
        - CM109199.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
