    CLADE : mammals 
    SPEC_NAME : DasNov 
    FULL_SPEC_NAME : Dasypus_novemcinctus 
    ALN_NAME : mDasNov 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 31
    NUM_ALL_CHR: 33
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_080673.1
        - NC_080674.1
        - NC_080675.1
        - NC_080676.1
        - NC_080677.1
        - NC_080678.1
        - NC_080679.1
        - NC_080680.1
        - NC_080681.1
        - NC_080682.1
        - NC_080683.1
        - NC_080684.1
        - NC_080685.1
        - NC_080686.1
        - NC_080687.1
        - NC_080688.1
        - NC_080689.1
        - NC_080690.1
        - NC_080691.1
        - NC_080692.1
        - NC_080693.1
        - NC_080694.1
        - NC_080695.1
        - NC_080696.1
        - NC_080697.1
        - NC_080698.1
        - NC_080699.1
        - NC_080700.1
        - NC_080701.1
        - NC_080702.1
        - NC_080703.1
        - NC_080704.1
        - NC_092216.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_080673.1
        - NC_080674.1
        - NC_080675.1
        - NC_080676.1
        - NC_080677.1
        - NC_080678.1
        - NC_080679.1
        - NC_080680.1
        - NC_080681.1
        - NC_080682.1
        - NC_080683.1
        - NC_080684.1
        - NC_080685.1
        - NC_080686.1
        - NC_080687.1
        - NC_080688.1
        - NC_080689.1
        - NC_080690.1
        - NC_080691.1
        - NC_080692.1
        - NC_080693.1
        - NC_080694.1
        - NC_080695.1
        - NC_080696.1
        - NC_080697.1
        - NC_080698.1
        - NC_080699.1
        - NC_080700.1
        - NC_080701.1
        - NC_080702.1
        - NC_080703.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
