    CLADE : mammals 
    SPEC_NAME : DugDug 
    FULL_SPEC_NAME : Dugong_dugon  
    ALN_NAME : mDugDug
    CHROM_START_CHR : CM
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 23
    NUM_ALL_CHR: 24
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM057460.1
        - CM057461.1
        - CM057462.1
        - CM057463.1
        - CM057464.1
        - CM057465.1
        - CM057466.1
        - CM057467.1
        - CM057468.1
        - CM057469.1
        - CM057470.1
        - CM057471.1
        - CM057472.1
        - CM057473.1
        - CM057474.1
        - CM057475.1
        - CM057476.1
        - CM057477.1
        - CM057478.1
        - CM057479.1
        - CM057480.1
        - CM057481.1
        - CM057482.1
        - CM057483.1
    AUTOSOMAL_CHROMOSOMES: 
        - CM057460.1
        - CM057461.1
        - CM057462.1
        - CM057463.1
        - CM057464.1
        - CM057465.1
        - CM057466.1
        - CM057467.1
        - CM057468.1
        - CM057469.1
        - CM057470.1
        - CM057471.1
        - CM057472.1
        - CM057473.1
        - CM057474.1
        - CM057475.1
        - CM057476.1
        - CM057477.1
        - CM057478.1
        - CM057479.1
        - CM057480.1
        - CM057481.1
        - CM057482.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
