    CLADE : mammals 
    SPEC_NAME : EleMax 
    FULL_SPEC_NAME : Elephas_maximus 
    ALN_NAME : mEleMax 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 27
    NUM_ALL_CHR: 29
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_064819.1
        - NC_064820.1
        - NC_064821.1
        - NC_064822.1
        - NC_064823.1
        - NC_064824.1
        - NC_064825.1
        - NC_064826.1
        - NC_064827.1
        - NC_064828.1
        - NC_064829.1
        - NC_064830.1
        - NC_064831.1
        - NC_064832.1
        - NC_064833.1
        - NC_064834.1
        - NC_064835.1
        - NC_064836.1
        - NC_064837.1
        - NC_064838.1
        - NC_064839.1
        - NC_064840.1
        - NC_064841.1
        - NC_064842.1
        - NC_064843.1
        - NC_064844.1
        - NC_064845.1
        - NC_064846.1
        - NC_064847.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_064819.1
        - NC_064820.1
        - NC_064821.1
        - NC_064822.1
        - NC_064823.1
        - NC_064824.1
        - NC_064825.1
        - NC_064826.1
        - NC_064827.1
        - NC_064828.1
        - NC_064829.1
        - NC_064830.1
        - NC_064831.1
        - NC_064832.1
        - NC_064833.1
        - NC_064834.1
        - NC_064835.1
        - NC_064836.1
        - NC_064837.1
        - NC_064838.1
        - NC_064839.1
        - NC_064840.1
        - NC_064841.1
        - NC_064842.1
        - NC_064843.1
        - NC_064844.1
        - NC_064845.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
