    CLADE : mammals 
    SPEC_NAME : EquCab 
    FULL_SPEC_NAME : Equus_caballus  
    ALN_NAME : mEquCab 
    CHROM_START_CHR : CM
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 31
    NUM_ALL_CHR: 33
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM071533.1
        - CM071534.1
        - CM071535.1
        - CM071536.1
        - CM071537.1
        - CM071538.1
        - CM071539.1
        - CM071540.1
        - CM071541.1
        - CM071542.1
        - CM071543.1
        - CM071544.1
        - CM071545.1
        - CM071546.1
        - CM071547.1
        - CM071548.1
        - CM071549.1
        - CM071550.1
        - CM071551.1
        - CM071552.1
        - CM071553.1
        - CM071554.1
        - CM071555.1
        - CM071556.1
        - CM071557.1
        - CM071558.1
        - CM071559.1
        - CM071560.1
        - CM071561.1
        - CM071562.1
        - CM071563.1
        - CM071564.1
        - CM071565.1 
    AUTOSOMAL_CHROMOSOMES: 
        - CM071533.1
        - CM071534.1
        - CM071535.1
        - CM071536.1
        - CM071537.1
        - CM071538.1
        - CM071539.1
        - CM071540.1
        - CM071541.1
        - CM071542.1
        - CM071543.1
        - CM071544.1
        - CM071545.1
        - CM071546.1
        - CM071547.1
        - CM071548.1
        - CM071549.1
        - CM071550.1
        - CM071551.1
        - CM071552.1
        - CM071553.1
        - CM071554.1
        - CM071555.1
        - CM071556.1
        - CM071557.1
        - CM071558.1
        - CM071559.1
        - CM071560.1
        - CM071561.1
        - CM071562.1
        - CM071563.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
