    CLADE : mammals 
    SPEC_NAME : GorGor 
    FULL_SPEC_NAME : Gorilla_gorilla 
    ALN_NAME : mGorGor 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 23
    NUM_ALL_CHR: 25
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_073224.2
        - NC_086017.1
        - NC_073227.2
        - NC_073228.2
        - NC_073229.2
        - NC_073230.2
        - NC_073231.2
        - NC_073232.2
        - NC_073233.2
        - NC_073234.2
        - NC_073235.2
        - NC_073236.2
        - NC_073237.2
        - NC_073238.2
        - NC_073239.2
        - NC_073240.2
        - NC_073241.2
        - NC_073242.2
        - NC_073243.2
        - NC_073244.2
        - NC_073245.2
        - NC_073246.2
        - NC_086017.1
        - NC_073247.2
        - NC_073248.2
    AUTOSOMAL_CHROMOSOMES: 
        - NC_073224.2
        - NC_086017.1
        - NC_073227.2
        - NC_073228.2
        - NC_073229.2
        - NC_073230.2
        - NC_073231.2
        - NC_073232.2
        - NC_073233.2
        - NC_073234.2
        - NC_073235.2
        - NC_073236.2
        - NC_073237.2
        - NC_073238.2
        - NC_073239.2
        - NC_073240.2
        - NC_073241.2
        - NC_073242.2
        - NC_073243.2
        - NC_073244.2
        - NC_073245.2
        - NC_073246.2
        - NC_086017.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
