    CLADE : mammals 
    SPEC_NAME : HipAmp 
    FULL_SPEC_NAME : Hippopotamus_amphibius 
    ALN_NAME : mHipAmp 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 17
    NUM_ALL_CHR: 18
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_080186.1
        - NC_080187.1
        - NC_080188.1
        - NC_080189.1
        - NC_080190.1
        - NC_080191.1
        - NC_080192.1
        - NC_080193.1
        - NC_080194.1
        - NC_080195.1
        - NC_080196.1
        - NC_080197.1
        - NC_080198.1
        - NC_080199.1
        - NC_080200.1
        - NC_080201.1
        - NC_080202.1
        - NC_080203.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_080186.1
        - NC_080187.1
        - NC_080188.1
        - NC_080189.1
        - NC_080190.1
        - NC_080191.1
        - NC_080192.1
        - NC_080193.1
        - NC_080194.1
        - NC_080195.1
        - NC_080196.1
        - NC_080197.1
        - NC_080198.1
        - NC_080199.1
        - NC_080200.1
        - NC_080201.1
        - NC_080202.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
