    CLADE : mammals 
    SPEC_NAME : JacJac 
    FULL_SPEC_NAME : Jaculus_jaculus 
    ALN_NAME : mJacJac 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 23
    NUM_ALL_CHR: 25
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_059102.1
        - NC_059103.1
        - NC_059104.1
        - NC_059105.1
        - NC_059106.1
        - NC_059107.1
        - NC_059108.1
        - NC_059109.1
        - NC_059110.1
        - NC_059111.1
        - NC_059112.1
        - NC_059113.1
        - NC_059114.1
        - NC_059115.1
        - NC_059116.1
        - NC_059117.1
        - NC_059118.1
        - NC_059119.1
        - NC_059120.1
        - NC_059121.1
        - NC_059122.1
        - NC_059123.1
        - NC_059124.1
        - NC_059125.1
        - NC_059126.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_059102.1
        - NC_059103.1
        - NC_059104.1
        - NC_059105.1
        - NC_059106.1
        - NC_059107.1
        - NC_059108.1
        - NC_059109.1
        - NC_059110.1
        - NC_059111.1
        - NC_059112.1
        - NC_059113.1
        - NC_059114.1
        - NC_059115.1
        - NC_059116.1
        - NC_059117.1
        - NC_059118.1
        - NC_059119.1
        - NC_059120.1
        - NC_059121.1
        - NC_059122.1
        - NC_059123.1
        - NC_059124.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
