    CLADE : mammals 
    SPEC_NAME : LemCat 
    FULL_SPEC_NAME : Lemur_catta 
    ALN_NAME : mLemCat 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 27
    NUM_ALL_CHR: 29
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_059128.1
        - NC_059129.1
        - NC_059130.1
        - NC_059131.1
        - NC_059132.1
        - NC_059133.1
        - NC_059134.1
        - NC_059135.1
        - NC_059136.1
        - NC_059137.1
        - NC_059138.1
        - NC_059139.1
        - NC_059140.1
        - NC_059141.1
        - NC_059142.1
        - NC_059143.1
        - NC_059144.1
        - NC_059145.1
        - NC_059146.1
        - NC_059147.1
        - NC_059148.1
        - NC_059149.1
        - NC_059150.1
        - NC_059151.1
        - NC_059152.1
        - NC_059153.1
        - NC_059154.1
        - NC_059155.1
        - NC_059156.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_059128.1
        - NC_059129.1
        - NC_059130.1
        - NC_059131.1
        - NC_059132.1
        - NC_059133.1
        - NC_059134.1
        - NC_059135.1
        - NC_059136.1
        - NC_059137.1
        - NC_059138.1
        - NC_059139.1
        - NC_059140.1
        - NC_059141.1
        - NC_059142.1
        - NC_059143.1
        - NC_059144.1
        - NC_059145.1
        - NC_059146.1
        - NC_059147.1
        - NC_059148.1
        - NC_059149.1
        - NC_059150.1
        - NC_059151.1
        - NC_059152.1
        - NC_059153.1
        - NC_059154.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
