    CLADE : mammals 
    SPEC_NAME : LoxAfr 
    FULL_SPEC_NAME : Loxodonta_africana
    ALN_NAME : mLoxAfr 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 27
    NUM_ALL_CHR: 29
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_087342.1
        - NC_087343.1
        - NC_087344.1
        - NC_087345.1
        - NC_087346.1
        - NC_087347.1
        - NC_087348.1
        - NC_087349.1
        - NC_087350.1
        - NC_087351.1
        - NC_087352.1
        - NC_087353.1
        - NC_087354.1
        - NC_087355.1
        - NC_087356.1
        - NC_087357.1
        - NC_087358.1
        - NC_087359.1
        - NC_087360.1
        - NC_087361.1
        - NC_087362.1
        - NC_087363.1
        - NC_087364.1
        - NC_087365.1
        - NC_087366.1
        - NC_087367.1
        - NC_087368.1
        - NC_087369.1
        - NC_087370.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_087342.1
        - NC_087343.1
        - NC_087344.1
        - NC_087345.1
        - NC_087346.1
        - NC_087347.1
        - NC_087348.1
        - NC_087349.1
        - NC_087350.1
        - NC_087351.1
        - NC_087352.1
        - NC_087353.1
        - NC_087354.1
        - NC_087355.1
        - NC_087356.1
        - NC_087357.1
        - NC_087358.1
        - NC_087359.1
        - NC_087360.1
        - NC_087361.1
        - NC_087362.1
        - NC_087363.1
        - NC_087364.1
        - NC_087365.1
        - NC_087366.1
        - NC_087367.1
        - NC_087368.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
