    CLADE : mammals 
    SPEC_NAME : ManPen 
    FULL_SPEC_NAME : Manis_pentadactyla 
    ALN_NAME : mManPen
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 19
    NUM_ALL_CHR: 21
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_080019.1
        - NC_080020.1
        - NC_080021.1
        - NC_080022.1
        - NC_080023.1
        - NC_080024.1
        - NC_080025.1
        - NC_080026.1
        - NC_080027.1
        - NC_080028.1
        - NC_080029.1
        - NC_080030.1
        - NC_080031.1
        - NC_080032.1
        - NC_080033.1
        - NC_080034.1
        - NC_080035.1
        - NC_080036.1
        - NC_080037.1
        - NC_080038.1
        - NC_080039.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_080019.1
        - NC_080020.1
        - NC_080021.1
        - NC_080022.1
        - NC_080023.1
        - NC_080024.1
        - NC_080025.1
        - NC_080026.1
        - NC_080027.1
        - NC_080028.1
        - NC_080029.1
        - NC_080030.1
        - NC_080031.1
        - NC_080032.1
        - NC_080033.1
        - NC_080034.1
        - NC_080035.1
        - NC_080036.1
        - NC_080037.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
