    CLADE : mammals 
    SPEC_NAME : MesBid 
    FULL_SPEC_NAME : Mesoplodon_bidens 
    ALN_NAME : mMesBid
    CHROM_START_CHR : OZ
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 20
    NUM_ALL_CHR: 22
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - OZ073212.1
        - OZ073213.1
        - OZ073214.1
        - OZ073215.1
        - OZ073216.1
        - OZ073218.1
        - OZ073219.1
        - OZ073220.1
        - OZ073221.1
        - OZ073222.1
        - OZ073223.1
        - OZ073224.1
        - OZ073225.1
        - OZ073226.1
        - OZ073227.1
        - OZ073228.1
        - OZ073229.1
        - OZ073230.1
        - OZ073231.1
        - OZ073233.1 
        - OZ073217.1
        - OZ073232.1
    AUTOSOMAL_CHROMOSOMES: 
        - OZ073212.1
        - OZ073213.1
        - OZ073214.1
        - OZ073215.1
        - OZ073216.1
        - OZ073218.1
        - OZ073219.1
        - OZ073220.1
        - OZ073221.1
        - OZ073222.1
        - OZ073223.1
        - OZ073224.1
        - OZ073225.1
        - OZ073226.1
        - OZ073227.1
        - OZ073228.1
        - OZ073229.1
        - OZ073230.1
        - OZ073231.1
        - OZ073233.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
