    CLADE : mammals 
    SPEC_NAME : MicMin 
    FULL_SPEC_NAME : Micromys_minutus 
    ALN_NAME : mMicMin 
    CHROM_START_CHR : OZ
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 33
    NUM_ALL_CHR: 34
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - OZ004780.1
        - OZ004782.1
        - OZ004783.1
        - OZ004784.1
        - OZ004785.1
        - OZ004786.1
        - OZ004787.1
        - OZ004788.1
        - OZ004789.1
        - OZ004790.1
        - OZ004791.1
        - OZ004792.1
        - OZ004793.1
        - OZ004794.1
        - OZ004795.1
        - OZ004796.1
        - OZ004797.1
        - OZ004798.1
        - OZ004799.1
        - OZ004800.1
        - OZ004801.1
        - OZ004802.1
        - OZ004803.1
        - OZ004804.1
        - OZ004805.1
        - OZ004806.1
        - OZ004807.1
        - OZ004808.1
        - OZ004809.1
        - OZ004810.1
        - OZ004811.1
        - OZ004812.1
        - OZ004813.1 
        - OZ004781.1
    AUTOSOMAL_CHROMOSOMES: 
        - OZ004780.1
        - OZ004782.1
        - OZ004783.1
        - OZ004784.1
        - OZ004785.1
        - OZ004786.1
        - OZ004787.1
        - OZ004788.1
        - OZ004789.1
        - OZ004790.1
        - OZ004791.1
        - OZ004792.1
        - OZ004793.1
        - OZ004794.1
        - OZ004795.1
        - OZ004796.1
        - OZ004797.1
        - OZ004798.1
        - OZ004799.1
        - OZ004800.1
        - OZ004801.1
        - OZ004802.1
        - OZ004803.1
        - OZ004804.1
        - OZ004805.1
        - OZ004806.1
        - OZ004807.1
        - OZ004808.1
        - OZ004809.1
        - OZ004810.1
        - OZ004811.1
        - OZ004812.1
        - OZ004813.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
