    CLADE : mammals 
    SPEC_NAME : OchPri 
    FULL_SPEC_NAME : Ochotona_princeps 
    ALN_NAME : mOchPri
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 33
    NUM_ALL_CHR: 35
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_080832.1
        - NC_080833.1
        - NC_080834.1
        - NC_080835.1
        - NC_080836.1
        - NC_080837.1
        - NC_080838.1
        - NC_080839.1
        - NC_080840.1
        - NC_080841.1
        - NC_080842.1
        - NC_080843.1
        - NC_080844.1
        - NC_080845.1
        - NC_080846.1
        - NC_080847.1
        - NC_080848.1
        - NC_080849.1
        - NC_080850.1
        - NC_080851.1
        - NC_080852.1
        - NC_080853.1
        - NC_080854.1
        - NC_080855.1
        - NC_080856.1
        - NC_080857.1
        - NC_080858.1
        - NC_080859.1
        - NC_080860.1
        - NC_080861.1
        - NC_080862.1
        - NC_080863.1
        - NC_080864.1
        - NC_080865.1
        - NC_080866.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_080832.1
        - NC_080833.1
        - NC_080834.1
        - NC_080835.1
        - NC_080836.1
        - NC_080837.1
        - NC_080838.1
        - NC_080839.1
        - NC_080840.1
        - NC_080841.1
        - NC_080842.1
        - NC_080843.1
        - NC_080844.1
        - NC_080845.1
        - NC_080846.1
        - NC_080847.1
        - NC_080848.1
        - NC_080849.1
        - NC_080850.1
        - NC_080851.1
        - NC_080852.1
        - NC_080853.1
        - NC_080854.1
        - NC_080855.1
        - NC_080856.1
        - NC_080857.1
        - NC_080858.1
        - NC_080859.1
        - NC_080860.1
        - NC_080861.1
        - NC_080862.1
        - NC_080863.1
        - NC_080864.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
