    CLADE : mammals 
    SPEC_NAME : OryCun 
    FULL_SPEC_NAME : Oryctolagus_cuniculus 
    ALN_NAME : mOryCun 
    CHROM_START_CHR : NC    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 21
    NUM_ALL_CHR: 22
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_091432.1
        - NC_091433.1
        - NC_091434.1
        - NC_091435.1
        - NC_091436.1
        - NC_091437.1
        - NC_091438.1
        - NC_091439.1
        - NC_091440.1
        - NC_091441.1
        - NC_091442.1
        - NC_091443.1
        - NC_091444.1
        - NC_091445.1
        - NC_091446.1
        - NC_091447.1
        - NC_091448.1
        - NC_091449.1
        - NC_091450.1
        - NC_091451.1
        - NC_091452.1
        - NC_091453.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_091432.1
        - NC_091433.1
        - NC_091434.1
        - NC_091435.1
        - NC_091436.1
        - NC_091437.1
        - NC_091438.1
        - NC_091439.1
        - NC_091440.1
        - NC_091441.1
        - NC_091442.1
        - NC_091443.1
        - NC_091444.1
        - NC_091445.1
        - NC_091446.1
        - NC_091447.1
        - NC_091448.1
        - NC_091449.1
        - NC_091450.1
        - NC_091451.1
        - NC_091452.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
