    CLADE : mammals 
    SPEC_NAME : PanPan 
    FULL_SPEC_NAME : Pan_paniscus 
    ALN_NAME : mPanPan 
    CHROM_START_CHR : NC    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 23
    NUM_ALL_CHR: 25
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_073249.2
        - NC_085926.1
        - NC_073252.2
        - NC_073253.2
        - NC_073254.2
        - NC_073255.2
        - NC_073256.2
        - NC_073257.2
        - NC_073258.2
        - NC_073259.2
        - NC_073260.2
        - NC_073261.2
        - NC_073262.2
        - NC_073263.2
        - NC_073264.2
        - NC_073265.2
        - NC_073266.2
        - NC_073267.2
        - NC_073268.2
        - NC_073269.2
        - NC_073270.2
        - NC_073271.2
        - NC_085927.1
        - NC_073272.2
        - NC_073273.2
    AUTOSOMAL_CHROMOSOMES: 
        - NC_073249.2
        - NC_085926.1
        - NC_073252.2
        - NC_073253.2
        - NC_073254.2
        - NC_073255.2
        - NC_073256.2
        - NC_073257.2
        - NC_073258.2
        - NC_073259.2
        - NC_073260.2
        - NC_073261.2
        - NC_073262.2
        - NC_073263.2
        - NC_073264.2
        - NC_073265.2
        - NC_073266.2
        - NC_073267.2
        - NC_073268.2
        - NC_073269.2
        - NC_073270.2
        - NC_073271.2
        - NC_085927.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
