    CLADE : mammals 
    SPEC_NAME : PonAbe 
    FULL_SPEC_NAME : Pongo_abelii 
    ALN_NAME : mPonAbe 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 23
    NUM_ALL_CHR: 25
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_071985.2
        - NC_085928.1
        - NC_071988.2
        - NC_071989.2
        - NC_071990.2
        - NC_071991.2
        - NC_071992.2
        - NC_071993.2
        - NC_071994.2
        - NC_071995.2
        - NC_071996.2
        - NC_071997.2
        - NC_071998.2
        - NC_071999.2
        - NC_072000.2
        - NC_072001.2
        - NC_072002.2
        - NC_072003.2
        - NC_072004.2
        - NC_072005.2
        - NC_072006.2
        - NC_072007.2
        - NC_085929.1
        - NC_072008.2
        - NC_072009.2
    AUTOSOMAL_CHROMOSOMES: 
        - NC_071985.2
        - NC_085928.1
        - NC_071988.2
        - NC_071989.2
        - NC_071990.2
        - NC_071991.2
        - NC_071992.2
        - NC_071993.2
        - NC_071994.2
        - NC_071995.2
        - NC_071996.2
        - NC_071997.2
        - NC_071998.2
        - NC_071999.2
        - NC_072000.2
        - NC_072001.2
        - NC_072002.2
        - NC_072003.2
        - NC_072004.2
        - NC_072005.2
        - NC_072006.2
        - NC_072007.2
        - NC_085929.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
