    CLADE : mammals 
    SPEC_NAME : PonPyg 
    FULL_SPEC_NAME : Pongo_pygmaeus 
    ALN_NAME : mPonPyg 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 23
    NUM_ALL_CHR: 25
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_072373.2
        - NC_072376.2
        - NC_072377.2
        - NC_072378.2
        - NC_072379.2
        - NC_072380.2
        - NC_072381.2
        - NC_072382.2
        - NC_072383.2
        - NC_072384.2
        - NC_072385.2
        - NC_072386.2
        - NC_072387.2
        - NC_072388.2
        - NC_072389.2
        - NC_072390.2
        - NC_072391.2
        - NC_072392.2
        - NC_072393.2
        - NC_072394.2
        - NC_072395.2
        - NC_085930.1
        - NC_085931.1
        - NC_001646.1 
        - NC_072396.2
        - NC_072397.2
    AUTOSOMAL_CHROMOSOMES: 
        - NC_072373.2
        - NC_072376.2
        - NC_072377.2
        - NC_072378.2
        - NC_072379.2
        - NC_072380.2
        - NC_072381.2
        - NC_072382.2
        - NC_072383.2
        - NC_072384.2
        - NC_072385.2
        - NC_072386.2
        - NC_072387.2
        - NC_072388.2
        - NC_072389.2
        - NC_072390.2
        - NC_072391.2
        - NC_072392.2
        - NC_072393.2
        - NC_072394.2
        - NC_072395.2
        - NC_085930.1
        - NC_085931.1
        - NC_001646.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
