    CLADE : mammals 
    SPEC_NAME : RatNor 
    FULL_SPEC_NAME : Rattus_norvegicus 
    ALN_NAME : mRatNor 
    CHROM_START_CHR : NC    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 20
    NUM_ALL_CHR: 22
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_051336.1
        - NC_051337.1
        - NC_051338.1
        - NC_051339.1
        - NC_051340.1
        - NC_051341.1
        - NC_051342.1
        - NC_051343.1
        - NC_051344.1
        - NC_051345.1
        - NC_051346.1
        - NC_051347.1
        - NC_051348.1
        - NC_051349.1
        - NC_051350.1
        - NC_051351.1
        - NC_051352.1
        - NC_051353.1
        - NC_051354.1
        - NC_051355.1
        - NC_051356.1
        - NC_051357.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_051336.1
        - NC_051337.1
        - NC_051338.1
        - NC_051339.1
        - NC_051340.1
        - NC_051341.1
        - NC_051342.1
        - NC_051343.1
        - NC_051344.1
        - NC_051345.1
        - NC_051346.1
        - NC_051347.1
        - NC_051348.1
        - NC_051349.1
        - NC_051350.1
        - NC_051351.1
        - NC_051352.1
        - NC_051353.1
        - NC_051354.1
        - NC_051355.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
