    CLADE : mammals 
    SPEC_NAME : RhiAff 
    FULL_SPEC_NAME : Rhinolophus_affinis 
    ALN_NAME : mRhiAff 
    CHROM_START_CHR : CM    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 30
    NUM_ALL_CHR: 31
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM093063.1
        - CM093064.1
        - CM093065.1
        - CM093066.1
        - CM093067.1
        - CM093068.1
        - CM093069.1
        - CM093070.1
        - CM093071.1
        - CM093072.1
        - CM093073.1
        - CM093074.1
        - CM093075.1
        - CM093076.1
        - CM093077.1
        - CM093078.1
        - CM093079.1
        - CM093080.1
        - CM093081.1
        - CM093082.1
        - CM093083.1
        - CM093084.1
        - CM093085.1
        - CM093086.1
        - CM093087.1
        - CM093088.1
        - CM093089.1
        - CM093090.1
        - CM093091.1
        - CM093092.1
        - CM093093.1
    AUTOSOMAL_CHROMOSOMES: 
        - CM093063.1
        - CM093064.1
        - CM093065.1
        - CM093066.1
        - CM093067.1
        - CM093068.1
        - CM093069.1
        - CM093070.1
        - CM093071.1
        - CM093072.1
        - CM093073.1
        - CM093074.1
        - CM093075.1
        - CM093076.1
        - CM093077.1
        - CM093078.1
        - CM093079.1
        - CM093080.1
        - CM093081.1
        - CM093082.1
        - CM093083.1
        - CM093084.1
        - CM093085.1
        - CM093086.1
        - CM093087.1
        - CM093088.1
        - CM093089.1
        - CM093090.1
        - CM093091.1
        - CM093092.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
