    CLADE : mammals 
    SPEC_NAME : RhiPer 
    FULL_SPEC_NAME : Rhinolophus_perniger 
    ALN_NAME : mRhiPer 
    CHROM_START_CHR : CM    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 15
    NUM_ALL_CHR: 17
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM093129.1
        - CM093130.1
        - CM093131.1
        - CM093132.1
        - CM093133.1
        - CM093134.1
        - CM093135.1
        - CM093136.1
        - CM093137.1
        - CM093138.1
        - CM093139.1
        - CM093140.1
        - CM093141.1
        - CM093142.1
        - CM093143.1
        - CM093144.1
        - CM093145.1 
    AUTOSOMAL_CHROMOSOMES: 
        - CM093129.1
        - CM093130.1
        - CM093131.1
        - CM093132.1
        - CM093133.1
        - CM093134.1
        - CM093135.1
        - CM093136.1
        - CM093137.1
        - CM093138.1
        - CM093139.1
        - CM093140.1
        - CM093141.1
        - CM093142.1
        - CM093143.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
