    CLADE : mammals 
    SPEC_NAME : RhiYon 
    FULL_SPEC_NAME : Rhinolophus_yonghoiseni 
    ALN_NAME : mRhiYon 
    CHROM_START_CHR : CM    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 14
    NUM_ALL_CHR: 14
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM093746.1
        - CM093747.1
        - CM093748.1
        - CM093749.1
        - CM093750.1
        - CM093751.1
        - CM093752.1
        - CM093753.1
        - CM093754.1
        - CM093755.1
        - CM093756.1
        - CM093757.1
        - CM093758.1
        - CM093759.1
    AUTOSOMAL_CHROMOSOMES: 
        - CM093746.1
        - CM093747.1
        - CM093748.1
        - CM093749.1
        - CM093750.1
        - CM093751.1
        - CM093752.1
        - CM093753.1
        - CM093754.1
        - CM093755.1
        - CM093756.1
        - CM093757.1
        - CM093758.1
        - CM093759.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
