    CLADE : mammals 
    SPEC_NAME : RhyNas 
    FULL_SPEC_NAME : Rhynchonycteris_naso 
    ALN_NAME : mRhyNas 
    CHROM_START_CHR : CM
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 10
    NUM_ALL_CHR: 12
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM073042.1
        - CM073043.1
        - CM073044.1
        - CM073045.1
        - CM073046.1
        - CM073047.1
        - CM073048.1
        - CM073049.1
        - CM073050.1
        - CM073051.1
        - CM073052.1
        - CM073053.1
    AUTOSOMAL_CHROMOSOMES: 
        - CM073042.1
        - CM073043.1
        - CM073044.1
        - CM073045.1
        - CM073046.1
        - CM073047.1
        - CM073048.1
        - CM073049.1
        - CM073050.1
        - CM073051.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
