    CLADE : mammals 
    SPEC_NAME : SusScr 
    FULL_SPEC_NAME : Sus_scrofa 
    ALN_NAME : mSusScr
    CHROM_START_CHR : CM
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 18
    NUM_ALL_CHR: 20
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM107792.1
        - CM107793.1
        - CM107794.1
        - CM107795.1
        - CM107796.1
        - CM107797.1
        - CM107798.1
        - CM107799.1
        - CM107800.1
        - CM107801.1
        - CM107802.1
        - CM107803.1
        - CM107804.1
        - CM107805.1
        - CM107806.1
        - CM107807.1
        - CM107808.1
        - CM107809.1
        - CM107810.1
        - CM107811.1 
    AUTOSOMAL_CHROMOSOMES: 
        - CM107792.1
        - CM107793.1
        - CM107794.1
        - CM107795.1
        - CM107796.1
        - CM107797.1
        - CM107798.1
        - CM107799.1
        - CM107800.1
        - CM107801.1
        - CM107802.1
        - CM107803.1
        - CM107804.1
        - CM107805.1
        - CM107806.1
        - CM107807.1
        - CM107808.1
        - CM107809.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
