    CLADE : mammals 
    SPEC_NAME : TacAcu 
    FULL_SPEC_NAME : Tachyglossus_aculeatus 
    ALN_NAME : mTacAcu 
    CHROM_START_CHR : NC    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 26
    NUM_ALL_CHR: 35
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_052066.1
        - NC_052067.1
        - NC_052068.1
        - NC_052069.1
        - NC_052070.1
        - NC_052071.1
        - NC_052072.1
        - NC_052073.1
        - NC_052074.1
        - NC_052075.1
        - NC_052076.1
        - NC_052077.1
        - NC_052078.1
        - NC_052079.1
        - NC_052080.1
        - NC_052081.1
        - NC_052082.1
        - NC_052083.1
        - NC_052084.1
        - NC_052085.1
        - NC_052086.1
        - NC_052087.1
        - NC_052088.1
        - NC_052089.1
        - NC_052090.1
        - NC_052091.1
        - NC_052092.1
        - NC_052093.1
        - NC_052094.1
        - NC_052095.1
        - NC_052096.1
        - NC_052097.1
        - NC_052098.1
        - NC_052099.1
        - NC_052100.1 
        - NC_052101.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_052066.1
        - NC_052067.1
        - NC_052068.1
        - NC_052069.1
        - NC_052070.1
        - NC_052071.1
        - NC_052072.1
        - NC_052073.1
        - NC_052074.1
        - NC_052075.1
        - NC_052076.1
        - NC_052077.1
        - NC_052078.1
        - NC_052079.1
        - NC_052080.1
        - NC_052081.1
        - NC_052082.1
        - NC_052083.1
        - NC_052084.1
        - NC_052085.1
        - NC_052086.1
        - NC_052087.1
        - NC_052088.1
        - NC_052089.1
        - NC_052090.1
        - NC_052091.1
        - NC_052092.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
