    CLADE : mammals 
    SPEC_NAME : TriInu 
    FULL_SPEC_NAME : Trichechus_inunguis 
    ALN_NAME : mTriInu 
    CHROM_START_CHR : CM
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 27
    NUM_ALL_CHR: 29
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM102146.1
        - CM102147.1
        - CM102148.1
        - CM102149.1
        - CM102150.1
        - CM102151.1
        - CM102152.1
        - CM102153.1
        - CM102154.1
        - CM102155.1
        - CM102156.1
        - CM102157.1
        - CM102158.1
        - CM102159.1
        - CM102160.1
        - CM102161.1
        - CM102162.1
        - CM102163.1
        - CM102164.1
        - CM102165.1
        - CM102166.1
        - CM102167.1
        - CM102168.1
        - CM102169.1
        - CM102170.1
        - CM102171.1
        - CM102172.1
        - CM102173.1
        - CM102174.1 
    AUTOSOMAL_CHROMOSOMES: 
        - CM102146.1
        - CM102147.1
        - CM102148.1
        - CM102149.1
        - CM102150.1
        - CM102151.1
        - CM102152.1
        - CM102153.1
        - CM102154.1
        - CM102155.1
        - CM102156.1
        - CM102157.1
        - CM102158.1
        - CM102159.1
        - CM102160.1
        - CM102161.1
        - CM102162.1
        - CM102163.1
        - CM102164.1
        - CM102165.1
        - CM102166.1
        - CM102167.1
        - CM102168.1
        - CM102169.1
        - CM102170.1
        - CM102171.1
        - CM102172.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
