    CLADE : mammals 
    SPEC_NAME : ZalCal 
    FULL_SPEC_NAME : Zalophus_californianus 
    ALN_NAME : mZalCal 
    CHROM_START_CHR : NC    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 17
    NUM_ALL_CHR: 19
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_045595.1
        - NC_045596.1
        - NC_045597.1
        - NC_045598.1
        - NC_045599.1
        - NC_045600.1
        - NC_045601.1
        - NC_045602.1
        - NC_045603.1
        - NC_045604.1
        - NC_045605.1
        - NC_045606.1
        - NC_045607.1
        - NC_045608.1
        - NC_045609.1
        - NC_045610.1
        - NC_045611.1
        - NC_045612.1
        - NC_045613.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_045595.1
        - NC_045596.1
        - NC_045597.1
        - NC_045598.1
        - NC_045599.1
        - NC_045600.1
        - NC_045601.1
        - NC_045602.1
        - NC_045603.1
        - NC_045604.1
        - NC_045605.1
        - NC_045606.1
        - NC_045607.1
        - NC_045608.1
        - NC_045609.1
        - NC_045610.1
        - NC_045611.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
