    CLADE : amphibians 
    SPEC_NAME : BomBom 
    FULL_SPEC_NAME : Bombina_bombina 
    ALN_NAME : aBomBom 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 12
    NUM_ALL_CHR: 12
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_069499.1
        - NC_069500.1
        - NC_069501.1
        - NC_069502.1
        - NC_069503.1
        - NC_069504.1
        - NC_069505.1
        - NC_069506.1
        - NC_069507.1
        - NC_069508.1
        - NC_069509.1
        - NC_069510.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_069499.1
        - NC_069500.1
        - NC_069501.1
        - NC_069502.1
        - NC_069503.1
        - NC_069504.1
        - NC_069505.1
        - NC_069506.1
        - NC_069507.1
        - NC_069508.1
        - NC_069509.1
        - NC_069510.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
