    CLADE : amphibians 
    SPEC_NAME : DisPic 
    FULL_SPEC_NAME : Discoglossus_pictus 
    ALN_NAME : aDisPic 
    CHROM_START_CHR : CM
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 14
    NUM_ALL_CHR: 14
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM050163.1
        - CM050164.1
        - CM050165.1
        - CM050166.1
        - CM050167.1
        - CM050168.1
        - CM050169.1
        - CM050170.1
        - CM050171.1
        - CM050172.1
        - CM050173.1
        - CM050174.1
        - CM050175.1
        - CM050176.1
    AUTOSOMAL_CHROMOSOMES: 
        - CM050163.1
        - CM050164.1
        - CM050165.1
        - CM050166.1
        - CM050167.1
        - CM050168.1
        - CM050169.1
        - CM050170.1
        - CM050171.1
        - CM050172.1
        - CM050173.1
        - CM050174.1
        - CM050175.1
        - CM050176.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
