    CLADE : amphibians 
    SPEC_NAME : EleCoq 
    FULL_SPEC_NAME : Eleutherodactylus_coqui 
    ALN_NAME : aEleCoq 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 13
    NUM_ALL_CHR: 13
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_089837.1
        - NC_089838.1
        - NC_089839.1
        - NC_089840.1
        - NC_089841.1
        - NC_089842.1
        - NC_089843.1
        - NC_089844.1
        - NC_089845.1
        - NC_089846.1
        - NC_089847.1
        - NC_089848.1
        - NC_089849.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_089837.1
        - NC_089838.1
        - NC_089839.1
        - NC_089840.1
        - NC_089841.1
        - NC_089842.1
        - NC_089843.1
        - NC_089844.1
        - NC_089845.1
        - NC_089846.1
        - NC_089847.1
        - NC_089848.1
        - NC_089849.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
