    CLADE : amphibians 
    SPEC_NAME : EngPus 
    FULL_SPEC_NAME : Engystomops_pustulosus 
    ALN_NAME : aEngPus 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 11
    NUM_ALL_CHR: 11
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_092411.1
        - NC_092412.1
        - NC_092413.1
        - NC_092414.1
        - NC_092415.1
        - NC_092416.1
        - NC_092417.1
        - NC_092418.1
        - NC_092419.1
        - NC_092420.1
        - NC_092421.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_092411.1
        - NC_092412.1
        - NC_092413.1
        - NC_092414.1
        - NC_092415.1
        - NC_092416.1
        - NC_092417.1
        - NC_092418.1
        - NC_092419.1
        - NC_092420.1
        - NC_092421.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
