    CLADE : amphibians 
    SPEC_NAME : GasCar 
    FULL_SPEC_NAME : Gastrophryne_carolinensis 
    ALN_NAME : aGasCar 
    CHROM_START_CHR : CM
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 11
    NUM_ALL_CHR: 11
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM051234.1
        - CM051235.1
        - CM051236.1
        - CM051237.1
        - CM051238.1
        - CM051239.1
        - CM051240.1
        - CM051241.1
        - CM051242.1
        - CM051243.1
        - CM051244.1
    AUTOSOMAL_CHROMOSOMES: 
        - CM051234.1
        - CM051235.1
        - CM051236.1
        - CM051237.1
        - CM051238.1
        - CM051239.1
        - CM051240.1
        - CM051241.1
        - CM051242.1
        - CM051243.1
        - CM051244.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
