    CLADE : amphibians 
    SPEC_NAME : LepFus 
    FULL_SPEC_NAME : Leptodactylus_fuscus 
    ALN_NAME : aLepFus 
    CHROM_START_CHR : CM
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 11
    NUM_ALL_CHR: 11
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM063204.1
        - CM063205.1
        - CM063206.1
        - CM063207.1
        - CM063208.1
        - CM063209.1
        - CM063210.1
        - CM063211.1
        - CM063212.1
        - CM063213.1
        - CM063214.1
    AUTOSOMAL_CHROMOSOMES: 
        - CM063204.1
        - CM063205.1
        - CM063206.1
        - CM063207.1
        - CM063208.1
        - CM063209.1
        - CM063210.1
        - CM063211.1
        - CM063212.1
        - CM063213.1
        - CM063214.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
