    CLADE : amphibians 
    SPEC_NAME : PleWal 
    FULL_SPEC_NAME : Pleurodeles_waltl 
    ALN_NAME : aPleWal 
    CHROM_START_CHR : CM    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 16
    NUM_ALL_CHR: 16
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM048897.1
        - CM048898.1
        - CM048899.1
        - CM048900.1
        - CM048901.1
        - CM048902.1
        - CM048903.1
        - CM048904.1
        - CM048905.1
        - CM048906.1
        - CM048907.1
        - CM048908.1
        - CM048909.1
        - CM048910.1
        - CM048911.1
        - CM048912.1
    AUTOSOMAL_CHROMOSOMES: 
        - CM048897.1
        - CM048898.1
        - CM048899.1
        - CM048900.1
        - CM048901.1
        - CM048902.1
        - CM048903.1
        - CM048904.1
        - CM048905.1
        - CM048906.1
        - CM048907.1
        - CM048908.1
        - CM048909.1
        - CM048910.1
        - CM048911.1
        - CM048912.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
