    CLADE : amphibians 
    SPEC_NAME : RanImi 
    FULL_SPEC_NAME : Ranitomeya_imitator 
    ALN_NAME : aRanImi 
    CHROM_START_CHR : NC    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 10
    NUM_ALL_CHR: 10
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_091282.1
        - NC_091283.1
        - NC_091284.1
        - NC_091285.1
        - NC_091286.1
        - NC_091287.1
        - NC_091288.1
        - NC_091289.1
        - NC_091290.1
        - NC_091291.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_091282.1
        - NC_091283.1
        - NC_091284.1
        - NC_091285.1
        - NC_091286.1
        - NC_091287.1
        - NC_091288.1
        - NC_091289.1
        - NC_091290.1
        - NC_091291.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
