    CLADE : birds 
    SPEC_NAME : AmmNel 
    FULL_SPEC_NAME : Ammospiza_nelsoni 
    ALN_NAME : bAmmNel 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 35
    NUM_ALL_CHR: 37
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 3 ## Rounded from 2.66
    ALL_CHROMOSOMES : 
        - NC_080633.1
        - NC_080634.1
        - NC_080635.1
        - NC_080636.1
        - NC_080637.1
        - NC_080638.1
        - NC_080639.1
        - NC_080640.1
        - NC_080641.1
        - NC_080642.1
        - NC_080643.1
        - NC_080644.1
        - NC_080645.1
        - NC_080646.1
        - NC_080647.1
        - NC_080648.1
        - NC_080649.1
        - NC_080650.1
        - NC_080651.1
        - NC_080652.1
        - NC_080653.1
        - NC_080654.1
        - NC_080655.1
        - NC_080656.1
        - NC_080657.1
        - NC_080658.1
        - NC_080659.1
        - NC_080660.1
        - NC_080661.1
        - NC_080662.1
        - NC_080663.1
        - NC_080664.1
        - NC_080665.1
        - NC_080666.1
        - NC_080667.1
        - NC_080668.1
        - NC_080669.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_080633.1
        - NC_080634.1
        - NC_080635.1
        - NC_080636.1
        - NC_080637.1
        - NC_080638.1
        - NC_080639.1
        - NC_080640.1
        - NC_080641.1
        - NC_080642.1
        - NC_080643.1
        - NC_080644.1
        - NC_080645.1
        - NC_080646.1
        - NC_080647.1
        - NC_080648.1
        - NC_080649.1
        - NC_080650.1
        - NC_080651.1
        - NC_080652.1
        - NC_080653.1
        - NC_080654.1
        - NC_080655.1
        - NC_080656.1
        - NC_080657.1
        - NC_080658.1
        - NC_080659.1
        - NC_080660.1
        - NC_080661.1
        - NC_080662.1
        - NC_080663.1
        - NC_080664.1
        - NC_080665.1
        - NC_080666.1
        - NC_080667.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
