    CLADE : birds 
    SPEC_NAME : CalAnn 
    FULL_SPEC_NAME : Calypte_anna 
    ALN_NAME : bCalAnn 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 33
    NUM_ALL_CHR: 35
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_044244.1
        - NC_044245.1
        - NC_044246.1
        - NC_044247.1
        - NC_044248.1
        - NC_044249.1
        - NC_044250.1
        - NC_044251.1
        - NC_044252.1
        - NC_044253.1
        - NC_044254.1
        - NC_044255.1
        - NC_044256.1
        - NC_044257.1
        - NC_044258.1
        - NC_044259.1
        - NC_044260.1
        - NC_044261.1
        - NC_044262.1
        - NC_044263.1
        - NC_044264.1
        - NC_044265.1
        - NC_044266.1
        - NC_044267.1
        - NC_044268.1
        - NC_044269.1
        - NC_044270.1
        - NC_044271.1
        - NC_044272.1
        - NC_044273.1
        - NC_044275.1
        - NC_044276.1 
        - NC_044274.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_044244.1
        - NC_044245.1
        - NC_044246.1
        - NC_044247.1
        - NC_044248.1
        - NC_044249.1
        - NC_044250.1
        - NC_044251.1
        - NC_044252.1
        - NC_044253.1
        - NC_044254.1
        - NC_044255.1
        - NC_044256.1
        - NC_044257.1
        - NC_044258.1
        - NC_044259.1
        - NC_044260.1
        - NC_044261.1
        - NC_044262.1
        - NC_044263.1
        - NC_044264.1
        - NC_044265.1
        - NC_044266.1
        - NC_044267.1
        - NC_044268.1
        - NC_044269.1
        - NC_044270.1
        - NC_044271.1
        - NC_044272.1
        - NC_044273.1
        - NC_044275.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
