    CLADE : birds 
    SPEC_NAME : CapEur 
    FULL_SPEC_NAME : Caprimulgus_europaeus 
    ALN_NAME : bCapEur 
    CHROM_START_CHR : OU
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 35
    NUM_ALL_CHR: 37
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 6 ## Rounded from 5.6 years
    ALL_CHROMOSOMES : 
        - OU015523.1
        - OU015524.1
        - OU015525.1
        - OU015526.1
        - OU015527.1
        - OU015528.1
        - OU015529.1
        - OU015530.1
        - OU015531.1
        - OU015532.1
        - OU015533.1
        - OU015534.1
        - OU015535.1
        - OU015536.1
        - OU015537.1
        - OU015538.1
        - OU015539.1
        - OU015540.1
        - OU015541.1
        - OU015542.1
        - OU015543.1
        - OU015544.1
        - OU015545.1
        - OU015546.1
        - OU015547.1
        - OU015548.1
        - OU015549.1
        - OU015550.1
        - OU015551.1
        - OU015552.1
        - OU015553.1
        - OU015554.1
        - OU015555.1
        - OU015556.1
        - OU015557.1
        - OU015558.1
        - OU015559.1
    AUTOSOMAL_CHROMOSOMES: 
        - OU015523.1
        - OU015524.1
        - OU015525.1
        - OU015526.1
        - OU015528.1
        - OU015529.1
        - OU015530.1
        - OU015531.1
        - OU015532.1
        - OU015533.1
        - OU015534.1
        - OU015535.1
        - OU015536.1
        - OU015538.1
        - OU015539.1
        - OU015540.1
        - OU015541.1
        - OU015542.1
        - OU015543.1
        - OU015544.1
        - OU015545.1
        - OU015546.1
        - OU015547.1
        - OU015548.1
        - OU015549.1
        - OU015550.1
        - OU015551.1
        - OU015552.1
        - OU015553.1
        - OU015554.1
        - OU015555.1
        - OU015556.1
        - OU015557.1
        - OU015558.1
        - OU015559.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
