    CLADE : birds 
    SPEC_NAME : ColLiv 
    FULL_SPEC_NAME : Columba_livia 
    ALN_NAME : bColLiv 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 39
    NUM_ALL_CHR: 41
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 6 ## Rounded from 5.8
    ALL_CHROMOSOMES : 
        - NC_088602.1
        - NC_088603.1
        - NC_088604.1
        - NC_088605.1
        - NC_088606.1
        - NC_088607.1
        - NC_088608.1
        - NC_088609.1
        - NC_088610.1
        - NC_088611.1
        - NC_088612.1
        - NC_088613.1
        - NC_088614.1
        - NC_088615.1
        - NC_088616.1
        - NC_088617.1
        - NC_088618.1
        - NC_088619.1
        - NC_088620.1
        - NC_088621.1
        - NC_088622.1
        - NC_088623.1
        - NC_088624.1
        - NC_088625.1
        - NC_088626.1
        - NC_088627.1
        - NC_088628.1
        - NC_088629.1
        - NC_088630.1
        - NC_088631.1
        - NC_088632.1
        - NC_088633.1
        - NC_088634.1
        - NC_088635.1
        - NC_088636.1
        - NC_088637.1
        - NC_088638.1
        - NC_088639.1
        - NC_088640.1
        - NC_088641.1
        - NC_088642.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_088602.1
        - NC_088603.1
        - NC_088604.1
        - NC_088605.1
        - NC_088606.1
        - NC_088607.1
        - NC_088608.1
        - NC_088609.1
        - NC_088610.1
        - NC_088611.1
        - NC_088612.1
        - NC_088613.1
        - NC_088614.1
        - NC_088615.1
        - NC_088616.1
        - NC_088617.1
        - NC_088618.1
        - NC_088619.1
        - NC_088620.1
        - NC_088621.1
        - NC_088622.1
        - NC_088623.1
        - NC_088624.1
        - NC_088625.1
        - NC_088626.1
        - NC_088627.1
        - NC_088628.1
        - NC_088629.1
        - NC_088630.1
        - NC_088631.1
        - NC_088632.1
        - NC_088633.1
        - NC_088634.1
        - NC_088635.1
        - NC_088636.1
        - NC_088637.1
        - NC_088638.1
        - NC_088639.1
        - NC_088640.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
