    CLADE : birds 
    SPEC_NAME : CygOlo 
    FULL_SPEC_NAME : Cygnus_olor 
    ALN_NAME : bCygOlo 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 34
    NUM_ALL_CHR: 34
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 12 ## rounded from 12.2
    ALL_CHROMOSOMES : 
        - NC_049169.1
        - NC_049170.1
        - NC_049171.1
        - NC_049172.1
        - NC_049173.1
        - NC_049174.1
        - NC_049175.1
        - NC_049176.1
        - NC_049177.1
        - NC_049178.1
        - NC_049179.1
        - NC_049180.1
        - NC_049181.1
        - NC_049182.1
        - NC_049183.1
        - NC_049184.1
        - NC_049185.1
        - NC_049186.1
        - NC_049187.1
        - NC_049188.1
        - NC_049189.1
        - NC_049190.1
        - NC_049191.1
        - NC_049192.1
        - NC_049193.1
        - NC_049194.1
        - NC_049195.1
        - NC_049196.1
        - NC_049197.1
        - NC_054087.1
        - NC_054088.1
        - NC_054089.1
        - NC_054090.1
        - NC_054091.1
        # - NC_054098.1
        # - NC_054099.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_049169.1
        - NC_049170.1
        - NC_049171.1
        - NC_049172.1
        - NC_049173.1
        - NC_049174.1
        - NC_049175.1
        - NC_049176.1
        - NC_049177.1
        - NC_049178.1
        - NC_049179.1
        - NC_049180.1
        - NC_049181.1
        - NC_049182.1
        - NC_049183.1
        - NC_049184.1
        - NC_049185.1
        - NC_049186.1
        - NC_049187.1
        - NC_049188.1
        - NC_049189.1
        - NC_049190.1
        - NC_049191.1
        - NC_049192.1
        - NC_049193.1
        - NC_049194.1
        - NC_049195.1
        - NC_049196.1
        - NC_049197.1
        - NC_054087.1
        - NC_054088.1
        - NC_054089.1
        - NC_054090.1
        - NC_054091.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
