    CLADE : birds 
    SPEC_NAME : EriRub 
    FULL_SPEC_NAME : Erithacus_rubecula 
    ALN_NAME : bEriRub 
    CHROM_START_CHR : LR
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 34
    NUM_ALL_CHR: 36
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 6
    ALL_CHROMOSOMES : 
        - LR812103.1
        - LR812104.1
        - LR812105.2
        - LR812106.1
        - LR812107.1
        - LR812108.1
        - LR812110.1
        - LR812111.1
        - LR812113.1
        - LR812114.1
        - LR812115.1
        - LR812116.1
        - LR812117.1
        - LR812118.1
        - LR812119.1
        - LR812120.1
        - LR812121.1
        - LR812122.1
        - LR812123.1
        - LR812124.1
        - LR812125.1
        - LR812126.1
        - LR812127.1
        - LR812128.1
        - LR812129.1
        - LR812131.1
        - LR812132.1
        - LR812133.1
        - LR812135.1
        - LR812137.1
        - LR812138.1
        - LR812130.2
        - LR812112.1
    AUTOSOMAL_CHROMOSOMES: 
        - LR812103.1
        - LR812104.1
        - LR812105.2
        - LR812106.1
        - LR812107.1
        - LR812108.1
        - LR812110.1
        - LR812111.1
        - LR812113.1
        - LR812114.1
        - LR812115.1
        - LR812116.1
        - LR812117.1
        - LR812118.1
        - LR812119.1
        - LR812120.1
        - LR812121.1
        - LR812122.1
        - LR812123.1
        - LR812124.1
        - LR812125.1
        - LR812126.1
        - LR812127.1
        - LR812128.1
        - LR812129.1
        - LR812131.1
        - LR812132.1
        - LR812133.1
        - LR812135.1
        - LR812137.1
        - LR812138.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
