    CLADE : birds 
    SPEC_NAME : ExcChi 
    FULL_SPEC_NAME : Excalfactoria_chinensis  
    ALN_NAME : bExcChi 
    REF_NAME : GCA_039878825.1 
    ALT_NAME : GCA_039878515.1 
    CHROM_START_CHR : CM
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 32
    NUM_ALL_CHR: 33
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM078496.1
        - CM078497.1
        - CM078498.1
        - CM078499.1
        - CM078500.1
        - CM078501.1
        - CM078502.1
        - CM078503.1
        - CM078504.1
        - CM078505.1
        - CM078506.1
        - CM078507.1
        - CM078508.1
        - CM078509.1
        - CM078510.1
        - CM078511.1
        - CM078512.1
        - CM078513.1
        - CM078514.1
        - CM078515.1
        - CM078516.1
        - CM078517.1
        - CM078518.1
        - CM078519.1
        - CM078520.1
        - CM078521.1
        - CM078522.1
        - CM078523.1
        - CM078524.1
        - CM078525.1
        - CM078526.1
        - CM078527.1
        - CM078528.1
    AUTOSOMAL_CHROMOSOMES: 
        - CM078496.1
        - CM078497.1
        - CM078498.1
        - CM078499.1
        - CM078500.1
        - CM078501.1
        - CM078502.1
        - CM078503.1
        - CM078504.1
        - CM078505.1
        - CM078506.1
        - CM078507.1
        - CM078508.1
        - CM078509.1
        - CM078510.1
        - CM078511.1
        - CM078512.1
        - CM078513.1
        - CM078514.1
        - CM078515.1
        - CM078516.1
        - CM078517.1
        - CM078518.1
        - CM078519.1
        - CM078520.1
        - CM078521.1
        - CM078522.1
        - CM078523.1
        - CM078524.1
        - CM078525.1
        - CM078526.1
        - CM078527.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
