    CLADE : birds 
    SPEC_NAME : GruAme 
    FULL_SPEC_NAME : Grus_americana  
    ALN_NAME : bGruAme 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 39
    NUM_ALL_CHR: 40
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 26 ## Rounded from 15.66
    ALL_CHROMOSOMES : 
        - NC_072852.1
        - NC_072853.1
        - NC_072854.1
        - NC_072855.1
        - NC_072856.1
        - NC_072857.1
        - NC_072858.1
        - NC_072859.1
        - NC_072860.1
        - NC_072861.1
        - NC_072862.1
        - NC_072863.1
        - NC_072864.1
        - NC_072865.1
        - NC_072866.1
        - NC_072867.1
        - NC_072868.1
        - NC_072869.1
        - NC_072870.1
        - NC_072871.1
        - NC_072872.1
        - NC_072873.1
        - NC_072874.1
        - NC_072875.1
        - NC_072876.1
        - NC_072877.1
        - NC_072878.1
        - NC_072879.1
        - NC_072880.1
        - NC_072881.1
        - NC_072882.1
        - NC_072883.1
        - NC_072884.1
        - NC_072885.1
        - NC_072886.1
        - NC_072887.1
        - NC_072888.1
        - NC_072889.1
        - NC_072890.1
        - NC_072891.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_072852.1
        - NC_072853.1
        - NC_072854.1
        - NC_072855.1
        - NC_072856.1
        - NC_072857.1
        - NC_072858.1
        - NC_072859.1
        - NC_072860.1
        - NC_072861.1
        - NC_072862.1
        - NC_072863.1
        - NC_072864.1
        - NC_072865.1
        - NC_072866.1
        - NC_072867.1
        - NC_072868.1
        - NC_072869.1
        - NC_072870.1
        - NC_072871.1
        - NC_072872.1
        - NC_072873.1
        - NC_072874.1
        - NC_072875.1
        - NC_072876.1
        - NC_072877.1
        - NC_072878.1
        - NC_072879.1
        - NC_072880.1
        - NC_072881.1
        - NC_072882.1
        - NC_072883.1
        - NC_072884.1
        - NC_072885.1
        - NC_072886.1
        - NC_072887.1
        - NC_072888.1
        - NC_072889.1
        - NC_072890.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
