    CLADE : birds 
    SPEC_NAME : HarHar 
    FULL_SPEC_NAME : Harpia_harpyja 
    ALN_NAME : bHarHar 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 28
    NUM_ALL_CHR: 30
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 20
    ALL_CHROMOSOMES : 
        - NC_068940.1
        - NC_068941.1
        - NC_068942.1
        - NC_068943.1
        - NC_068944.1
        - NC_068945.1
        - NC_068946.1
        - NC_068947.1
        - NC_068948.1
        - NC_068949.1
        - NC_068950.1
        - NC_068951.1
        - NC_068952.1
        - NC_068953.1
        - NC_068954.1
        - NC_068955.1
        - NC_068956.1
        - NC_068957.1
        - NC_068958.1
        - NC_068959.1
        - NC_068960.1
        - NC_068961.1
        - NC_068962.1
        - NC_068963.1
        - NC_068964.1
        - NC_068965.1
        - NC_068966.1
        - NC_068967.1
        - NC_068968.1
        - NC_068969.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_068940.1
        - NC_068941.1
        - NC_068942.1
        - NC_068943.1
        - NC_068944.1
        - NC_068945.1
        - NC_068946.1
        - NC_068947.1
        - NC_068948.1
        - NC_068949.1
        - NC_068950.1
        - NC_068951.1
        - NC_068952.1
        - NC_068953.1
        - NC_068954.1
        - NC_068955.1
        - NC_068956.1
        - NC_068957.1
        - NC_068958.1
        - NC_068959.1
        - NC_068960.1
        - NC_068961.1
        - NC_068962.1
        - NC_068963.1
        - NC_068964.1
        - NC_068965.1
        - NC_068966.1
        - NC_068967.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
