    CLADE : birds 
    SPEC_NAME : HelExo 
    FULL_SPEC_NAME : Heliangelus_exortis 
    ALN_NAME : bHelExo 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 31
    NUM_ALL_CHR: 33
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 2 ## rounded from 2.4
    ALL_CHROMOSOMES : 
        - NC_092422.1
        - NC_092423.1
        - NC_092424.1
        - NC_092425.1
        - NC_092426.1
        - NC_092427.1
        - NC_092428.1
        - NC_092429.1
        - NC_092430.1
        - NC_092431.1
        - NC_092432.1
        - NC_092433.1
        - NC_092434.1
        - NC_092435.1
        - NC_092436.1
        - NC_092437.1
        - NC_092438.1
        - NC_092439.1
        - NC_092440.1
        - NC_092441.1
        - NC_092442.1
        - NC_092443.1
        - NC_092444.1
        - NC_092445.1
        - NC_092446.1
        - NC_092447.1
        - NC_092448.1
        - NC_092449.1
        - NC_092450.1
        - NC_092451.1
        - NC_092452.1
        - NC_092453.1
        - NC_092454.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_092422.1
        - NC_092423.1
        - NC_092424.1
        - NC_092425.1
        - NC_092426.1
        - NC_092427.1
        - NC_092428.1
        - NC_092429.1
        - NC_092430.1
        - NC_092431.1
        - NC_092432.1
        - NC_092433.1
        - NC_092434.1
        - NC_092435.1
        - NC_092436.1
        - NC_092437.1
        - NC_092438.1
        - NC_092439.1
        - NC_092440.1
        - NC_092441.1
        - NC_092442.1
        - NC_092443.1
        - NC_092444.1
        - NC_092445.1
        - NC_092446.1
        - NC_092447.1
        - NC_092448.1
        - NC_092449.1
        - NC_092450.1
        - NC_092451.1
        - NC_092452.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
