    CLADE : birds 
    SPEC_NAME : HemCom 
    FULL_SPEC_NAME : Hemiprocne_comata 
    ALN_NAME : bHemCom 
    CHROM_START_CHR : CM
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 29
    NUM_ALL_CHR: 31
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 7.5 
    ALL_CHROMOSOMES : 
        - CM036586.1
        - CM036587.1
        - CM036588.1
        - CM036589.1
        - CM036590.1
        - CM036591.1
        - CM036592.1
        - CM036593.1
        - CM036594.1
        - CM036595.1
        - CM036596.1
        - CM036597.1
        - CM036598.1
        - CM036599.1
        - CM036600.1
        - CM036601.1
        - CM036602.1
        - CM036603.1
        - CM036604.1
        - CM036605.1
        - CM036606.1
        - CM036607.1
        - CM036608.1
        - CM036609.1
        - CM036610.1
        - CM036611.1
        - CM036612.1
        - CM036613.1
        - CM036614.1
        - CM036615.1
        - CM036616.1
    AUTOSOMAL_CHROMOSOMES: 
        - CM036586.1
        - CM036587.1
        - CM036588.1
        - CM036589.1
        - CM036590.1
        - CM036591.1
        - CM036592.1
        - CM036593.1
        - CM036594.1
        - CM036595.1
        - CM036596.1
        - CM036597.1
        - CM036598.1
        - CM036599.1
        - CM036600.1
        - CM036601.1
        - CM036602.1
        - CM036603.1
        - CM036604.1
        - CM036605.1
        - CM036606.1
        - CM036607.1
        - CM036608.1
        - CM036609.1
        - CM036610.1
        - CM036611.1
        - CM036612.1
        - CM036613.1
        - CM036614.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
