    CLADE : birds 
    SPEC_NAME : HirRus 
    FULL_SPEC_NAME : Hirundo_rustica 
    ALN_NAME : bHirRus 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 39
    NUM_ALL_CHR: 41
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 4 ## rounded from 3.9
    ALL_CHROMOSOMES : 
        - NC_053450.1
        - NC_053451.1
        - NC_053452.1
        - NC_053453.1
        - NC_053454.1
        - NC_053455.1
        - NC_053456.1
        - NC_053457.1
        - NC_053458.1
        - NC_053459.1
        - NC_053460.1
        - NC_053461.1
        - NC_053462.1
        - NC_053463.1
        - NC_053464.1
        - NC_053465.1
        - NC_053466.1
        - NC_053467.1
        - NC_053468.1
        - NC_053469.1
        - NC_053470.1
        - NC_053471.1
        - NC_053472.1
        - NC_053473.1
        - NC_053474.1
        - NC_053475.1
        - NC_053476.1
        - NC_053477.1
        - NC_053478.1
        - NC_053479.1
        - NC_053480.1
        - NC_053481.1
        - NC_053482.1
        - NC_053483.1
        - NC_053484.1
        - NC_053485.1
        - NC_053486.1
        - NC_053487.1
        - NC_053488.1
        ## - NC_080708.1 -- These two chromosomes are not found in the paf file and as such are being excluded from analysis
        ## - NC_080709.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_053450.1
        - NC_053451.1
        - NC_053452.1
        - NC_053453.1
        - NC_053454.1
        - NC_053455.1
        - NC_053456.1
        - NC_053457.1
        - NC_053458.1
        - NC_053459.1
        - NC_053460.1
        - NC_053461.1
        - NC_053462.1
        - NC_053463.1
        - NC_053464.1
        - NC_053465.1
        - NC_053466.1
        - NC_053467.1
        - NC_053468.1
        - NC_053469.1
        - NC_053470.1
        - NC_053471.1
        - NC_053472.1
        - NC_053473.1
        - NC_053474.1
        - NC_053475.1
        - NC_053476.1
        - NC_053477.1
        - NC_053478.1
        - NC_053479.1
        - NC_053480.1
        - NC_053481.1
        - NC_053482.1
        - NC_053483.1
        - NC_053484.1
        - NC_053485.1
        - NC_053486.1
        ## - NC_080708.1
        ## - NC_080709.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
