    CLADE : birds 
    SPEC_NAME : LarMic 
    FULL_SPEC_NAME : Larus_michahellis 
    ALN_NAME : bLarMic 
    CHROM_START_CHR : OZ
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 33
    NUM_ALL_CHR: 35
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 11.5 
    ALL_CHROMOSOMES : 
        - OZ118746.1
        - OZ118747.1
        - OZ118748.1
        - OZ118749.1
        - OZ118751.1
        - OZ118752.1
        - OZ118753.1
        - OZ118754.1
        - OZ118755.1
        - OZ118757.1
        - OZ118758.1
        - OZ118759.1
        - OZ118760.1
        - OZ118761.1
        - OZ118762.1
        - OZ118763.1
        - OZ118764.1
        - OZ118765.1
        - OZ118766.1
        - OZ118767.1
        - OZ118768.1
        - OZ118769.1
        - OZ118770.1
        - OZ118771.1
        - OZ118772.1
        - OZ118773.1
        - OZ118774.1
        - OZ118775.1
        - OZ118776.1
        - OZ118777.1
        - OZ118778.1
        - OZ118779.1
        - OZ118780.1
        - OZ118756.1
        - OZ118750.1
    AUTOSOMAL_CHROMOSOMES: 
        - OZ118746.1
        - OZ118747.1
        - OZ118748.1
        - OZ118749.1
        - OZ118751.1
        - OZ118752.1
        - OZ118753.1
        - OZ118754.1
        - OZ118755.1
        - OZ118757.1
        - OZ118758.1
        - OZ118759.1
        - OZ118760.1
        - OZ118761.1
        - OZ118762.1
        - OZ118763.1
        - OZ118764.1
        - OZ118765.1
        - OZ118766.1
        - OZ118767.1
        - OZ118768.1
        - OZ118769.1
        - OZ118770.1
        - OZ118771.1
        - OZ118772.1
        - OZ118773.1
        - OZ118774.1
        - OZ118775.1
        - OZ118776.1
        - OZ118777.1
        - OZ118778.1
        - OZ118779.1
        - OZ118780.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
