    CLADE : birds 
    SPEC_NAME : MelMel 
    FULL_SPEC_NAME : Melospiza_melodia 
    ALN_NAME : bMelMel 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 31
    NUM_ALL_CHR: 33
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_086194.1
        - NC_086195.1
        - NC_086196.1
        - NC_086197.1
        - NC_086198.1
        - NC_086199.1
        - NC_086200.1
        - NC_086201.1
        - NC_086202.1
        - NC_086203.1
        - NC_086204.1
        - NC_086205.1
        - NC_086206.1
        - NC_086207.1
        - NC_086208.1
        - NC_086209.1
        - NC_086210.1
        - NC_086211.1
        - NC_086212.1
        - NC_086213.1
        - NC_086214.1
        - NC_086215.1
        - NC_086216.1
        - NC_086217.1
        - NC_086218.1
        - NC_086219.1
        - NC_086220.1
        - NC_086221.1
        - NC_086222.1
        - NC_086223.1
        - NC_086224.1
        - NC_086225.1
        - NC_086226.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_086194.1
        - NC_086195.1
        - NC_086196.1
        - NC_086197.1
        - NC_086198.1
        - NC_086199.1
        - NC_086200.1
        - NC_086201.1
        - NC_086202.1
        - NC_086203.1
        - NC_086204.1
        - NC_086205.1
        - NC_086206.1
        - NC_086207.1
        - NC_086208.1
        - NC_086209.1
        - NC_086210.1
        - NC_086211.1
        - NC_086212.1
        - NC_086213.1
        - NC_086214.1
        - NC_086215.1
        - NC_086216.1
        - NC_086217.1
        - NC_086218.1
        - NC_086219.1
        - NC_086220.1
        - NC_086221.1
        - NC_086222.1
        - NC_086223.1
        - NC_086224.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
