    CLADE : birds 
    SPEC_NAME : MerNub 
    FULL_SPEC_NAME : Merops_nubicus 
    ALN_NAME : bMerNub 
    CHROM_START_CHR : CM
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 34
    NUM_ALL_CHR: 36
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM020380.1
        - CM020381.1
        - CM020382.1
        - CM020383.1
        - CM020384.1
        - CM020385.1
        - CM020386.1
        - CM020387.1
        - CM020388.1
        - CM020389.1
        - CM020390.1
        - CM020391.1
        - CM020392.1
        - CM020393.1
        - CM020394.1
        - CM020395.1
        - CM020396.1
        - CM020397.1
        - CM020398.1
        - CM020399.1
        - CM020400.1
        - CM020401.1
        - CM020402.1
        - CM020403.1
        - CM020404.1
        - CM020405.1
        - CM020406.1
        - CM020407.1
        - CM020408.1
        - CM020409.1
        - CM020410.1
        - CM020411.1
        - CM020412.1
        - CM020413.1
        - CM020414.1
        - CM020415.1
    AUTOSOMAL_CHROMOSOMES: 
        - CM020380.1
        - CM020381.1
        - CM020382.1
        - CM020383.1
        - CM020384.1
        - CM020385.1
        - CM020386.1
        - CM020387.1
        - CM020388.1
        - CM020389.1
        - CM020390.1
        - CM020391.1
        - CM020392.1
        - CM020393.1
        - CM020394.1
        - CM020395.1
        - CM020396.1
        - CM020397.1
        - CM020398.1
        - CM020399.1
        - CM020400.1
        - CM020401.1
        - CM020402.1
        - CM020403.1
        - CM020404.1
        - CM020405.1
        - CM020406.1
        - CM020407.1
        - CM020408.1
        - CM020409.1
        - CM020410.1
        - CM020411.1
        - CM020412.1
        - CM020413.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
