    CLADE : birds 
    SPEC_NAME : MerOct 
    FULL_SPEC_NAME : Mergus_octosetaceus 
    ALN_NAME : bMerOct 
    CHROM_START_CHR : CM
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 34
    NUM_ALL_CHR: 36
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM072283.1
        - CM072284.1
        - CM072285.1
        - CM072286.1
        - CM072287.1
        - CM072288.1
        - CM072289.1
        - CM072290.1
        - CM072291.1
        - CM072292.1
        - CM072293.1
        - CM072294.1
        - CM072295.1
        - CM072296.1
        - CM072297.1
        - CM072298.1
        - CM072299.1
        - CM072300.1
        - CM072301.1
        - CM072302.1
        - CM072303.1
        - CM072304.1
        - CM072305.1
        - CM072306.1
        - CM072307.1
        - CM072308.1
        - CM072309.1
        - CM072310.1
        - CM072311.1
        - CM072312.1
        - CM072313.1
        - CM072314.1
        - CM072315.1
        - CM072316.1
        - CM072317.1 
        - CM072318.1 
    AUTOSOMAL_CHROMOSOMES: 
        - CM072283.1
        - CM072284.1
        - CM072285.1
        - CM072286.1
        - CM072287.1
        - CM072288.1
        - CM072289.1
        - CM072290.1
        - CM072291.1
        - CM072292.1
        - CM072293.1
        - CM072294.1
        - CM072295.1
        - CM072296.1
        - CM072297.1
        - CM072298.1
        - CM072299.1
        - CM072300.1
        - CM072301.1
        - CM072302.1
        - CM072303.1
        - CM072304.1
        - CM072305.1
        - CM072306.1
        - CM072307.1
        - CM072308.1
        - CM072309.1
        - CM072310.1
        - CM072311.1
        - CM072312.1
        - CM072313.1
        - CM072314.1
        - CM072315.1
        - CM072316.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
