    CLADE : birds 
    SPEC_NAME : NycGra 
    FULL_SPEC_NAME : Nyctibius_grandis 
    ALN_NAME : bNycGra 
    CHROM_START_CHR : NC    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 36
    NUM_ALL_CHR: 38
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_090658.1
        - NC_090659.1
        - NC_090660.1
        - NC_090661.1
        - NC_090662.1
        - NC_090663.1
        - NC_090664.1
        - NC_090665.1
        - NC_090666.1
        - NC_090667.1
        - NC_090668.1
        - NC_090669.1
        - NC_090670.1
        - NC_090671.1
        - NC_090672.1
        - NC_090673.1
        - NC_090674.1
        - NC_090675.1
        - NC_090676.1
        - NC_090677.1
        - NC_090678.1
        - NC_090679.1
        - NC_090680.1
        - NC_090681.1
        - NC_090682.1
        - NC_090683.1
        - NC_090684.1
        - NC_090685.1
        - NC_090686.1
        - NC_090687.1
        - NC_090688.1
        - NC_090689.1
        - NC_090690.1
        - NC_090691.1
        - NC_090692.1
        - NC_090693.1
        - NC_090694.1
        - NC_090695.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_090658.1
        - NC_090659.1
        - NC_090660.1
        - NC_090661.1
        - NC_090662.1
        - NC_090663.1
        - NC_090664.1
        - NC_090665.1
        - NC_090666.1
        - NC_090667.1
        - NC_090668.1
        - NC_090669.1
        - NC_090670.1
        - NC_090671.1
        - NC_090672.1
        - NC_090673.1
        - NC_090674.1
        - NC_090675.1
        - NC_090676.1
        - NC_090677.1
        - NC_090678.1
        - NC_090679.1
        - NC_090680.1
        - NC_090681.1
        - NC_090682.1
        - NC_090683.1
        - NC_090684.1
        - NC_090685.1
        - NC_090686.1
        - NC_090687.1
        - NC_090688.1
        - NC_090689.1
        - NC_090690.1
        - NC_090691.1
        - NC_090692.1
        - NC_090693.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
