    CLADE : birds 
    SPEC_NAME : PasDom 
    FULL_SPEC_NAME : Passer_domesticus  
    ALN_NAME : bPasDom 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 37
    NUM_ALL_CHR: 39
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_087474.1
        - NC_087475.1
        - NC_087476.1
        - NC_087477.1
        - NC_087478.1
        - NC_087479.1
        - NC_087480.1
        - NC_087481.1
        - NC_087482.1
        - NC_087483.1
        - NC_087484.1
        - NC_087485.1
        - NC_087486.1
        - NC_087487.1
        - NC_087488.1
        - NC_087489.1
        - NC_087490.1
        - NC_087491.1
        - NC_087492.1
        - NC_087493.1
        - NC_087494.1
        - NC_087495.1
        - NC_087496.1
        - NC_087497.1
        - NC_087498.1
        - NC_087499.1
        - NC_087500.1
        - NC_087501.1
        - NC_087502.1
        - NC_087503.1
        - NC_087504.1
        - NC_087505.1
        - NC_087506.1
        - NC_087507.1
        - NC_087508.1
        - NC_087509.1
        - NC_087510.1
        - NC_087511.1
        - NC_087512.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_087474.1
        - NC_087475.1
        - NC_087476.1
        - NC_087477.1
        - NC_087478.1
        - NC_087479.1
        - NC_087480.1
        - NC_087481.1
        - NC_087482.1
        - NC_087483.1
        - NC_087484.1
        - NC_087485.1
        - NC_087486.1
        - NC_087487.1
        - NC_087488.1
        - NC_087489.1
        - NC_087490.1
        - NC_087491.1
        - NC_087492.1
        - NC_087493.1
        - NC_087494.1
        - NC_087495.1
        - NC_087496.1
        - NC_087497.1
        - NC_087498.1
        - NC_087499.1
        - NC_087500.1
        - NC_087501.1
        - NC_087502.1
        - NC_087503.1
        - NC_087504.1
        - NC_087505.1
        - NC_087506.1
        - NC_087507.1
        - NC_087508.1
        - NC_087509.1
        - NC_087510.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
