    CLADE : birds 
    SPEC_NAME : PelCri 
    FULL_SPEC_NAME : Pelecanus_crispus 
    ALN_NAME : bPelCri 
    CHROM_START_CHR : CM    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 32
    NUM_ALL_CHR: 34
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM060000.1
        - CM060001.1
        - CM060002.1
        - CM060003.1
        - CM060004.1
        - CM060005.1
        - CM060006.1
        - CM060007.1
        - CM060008.1
        - CM060009.1
        - CM060010.1
        - CM060011.1
        - CM060012.1
        - CM060013.1
        - CM060014.1
        - CM060015.1
        - CM060016.1
        - CM060017.1
        - CM060018.1
        - CM060019.1
        - CM060020.1
        - CM060021.1
        - CM060022.1
        - CM060023.1
        - CM060024.1
        - CM060025.1
        - CM060026.1
        - CM060027.1
        - CM060028.1
        - CM060029.1
        - CM060030.1
        - CM060031.1
        - CM060032.1
        - CM060033.1 
    AUTOSOMAL_CHROMOSOMES: 
        - CM060000.1
        - CM060001.1
        - CM060002.1
        - CM060003.1
        - CM060004.1
        - CM060005.1
        - CM060006.1
        - CM060007.1
        - CM060008.1
        - CM060009.1
        - CM060010.1
        - CM060011.1
        - CM060012.1
        - CM060013.1
        - CM060014.1
        - CM060015.1
        - CM060016.1
        - CM060017.1
        - CM060018.1
        - CM060019.1
        - CM060020.1
        - CM060021.1
        - CM060022.1
        - CM060023.1
        - CM060024.1
        - CM060025.1
        - CM060026.1
        - CM060027.1
        - CM060028.1
        - CM060029.1
        - CM060030.1
        - CM060031.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
