    CLADE : birds 
    SPEC_NAME : PhaAri 
    FULL_SPEC_NAME : Phalacrocorax_aristotelis 
    ALN_NAME : bPhaAri 
    CHROM_START_CHR : OX    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 34
    NUM_ALL_CHR: 36
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - OX451222.1
        - OX451223.1
        - OX451224.1
        - OX451225.1
        - OX451227.1
        - OX451228.1
        - OX451229.1
        - OX451230.1
        - OX451231.1
        - OX451233.1
        - OX451234.1
        - OX451235.1
        - OX451236.1
        - OX451237.1
        - OX451238.1
        - OX451239.1
        - OX451240.1
        - OX451241.1
        - OX451242.1
        - OX451243.1
        - OX451244.1
        - OX451245.1
        - OX451246.1
        - OX451247.1
        - OX451248.1
        - OX451249.1
        - OX451250.1
        - OX451251.1
        - OX451252.1
        - OX451253.1
        - OX451254.1
        - OX451255.1
        - OX451256.1
        - OX451257.1 
        - OX451232.1
        - OX451226.1
    AUTOSOMAL_CHROMOSOMES: 
        - OX451222.1
        - OX451223.1
        - OX451224.1
        - OX451225.1
        - OX451227.1
        - OX451228.1
        - OX451229.1
        - OX451230.1
        - OX451231.1
        - OX451233.1
        - OX451234.1
        - OX451235.1
        - OX451236.1
        - OX451237.1
        - OX451238.1
        - OX451239.1
        - OX451240.1
        - OX451241.1
        - OX451242.1
        - OX451243.1
        - OX451244.1
        - OX451245.1
        - OX451246.1
        - OX451247.1
        - OX451248.1
        - OX451249.1
        - OX451250.1
        - OX451251.1
        - OX451252.1
        - OX451253.1
        - OX451254.1
        - OX451255.1
        - OX451256.1
        - OX451257.1 
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
