    CLADE : birds 
    SPEC_NAME : PhaSup 
    FULL_SPEC_NAME : Phaethornis_superciliosus 
    ALN_NAME : bPhaSup 
    CHROM_START_CHR : CM    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 35
    NUM_ALL_CHR: 36
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - CM104660.1
        - CM104661.1
        - CM104662.1
        - CM104663.1
        - CM104664.1
        - CM104665.1
        - CM104666.1
        - CM104667.1
        - CM104668.1
        - CM104669.1
        - CM104670.1
        - CM104671.1
        - CM104672.1
        - CM104673.1
        - CM104674.1
        - CM104675.1
        - CM104676.1
        - CM104677.1
        - CM104678.1
        - CM104679.1
        - CM104680.1
        - CM104681.1
        - CM104682.1
        - CM104683.1
        - CM104684.1
        - CM104685.1
        - CM104686.1
        - CM104687.1
        - CM104688.1
        - CM104689.1
        - CM104690.1
        - CM104691.1
        - CM104692.1
        - CM104693.1
        - CM104694.1
        - CM104695.1 
    AUTOSOMAL_CHROMOSOMES: 
        - CM104660.1
        - CM104661.1
        - CM104662.1
        - CM104663.1
        - CM104664.1
        - CM104665.1
        - CM104666.1
        - CM104667.1
        - CM104668.1
        - CM104669.1
        - CM104670.1
        - CM104671.1
        - CM104672.1
        - CM104673.1
        - CM104674.1
        - CM104675.1
        - CM104676.1
        - CM104677.1
        - CM104678.1
        - CM104679.1
        - CM104680.1
        - CM104681.1
        - CM104682.1
        - CM104683.1
        - CM104684.1
        - CM104685.1
        - CM104686.1
        - CM104687.1
        - CM104688.1
        - CM104689.1
        - CM104690.1
        - CM104691.1
        - CM104692.1
        - CM104693.1
        - CM104694.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
