    CLADE : birds 
    SPEC_NAME : PoeAtr 
    FULL_SPEC_NAME : Poecile_atricapillus 
    ALN_NAME : bPoeAtr
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 39
    NUM_ALL_CHR: 41
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_081249.1
        - NC_081250.1
        - NC_081251.1
        - NC_081252.1
        - NC_081253.1
        - NC_081254.1
        - NC_081255.1
        - NC_081256.1
        - NC_081257.1
        - NC_081258.1
        - NC_081259.1
        - NC_081260.1
        - NC_081261.1
        - NC_081262.1
        - NC_081263.1
        - NC_081264.1
        - NC_081265.1
        - NC_081266.1
        - NC_081267.1
        - NC_081268.1
        - NC_081269.1
        - NC_081270.1
        - NC_081271.1
        - NC_081272.1
        - NC_081273.1
        - NC_081274.1
        - NC_081275.1
        - NC_081276.1
        - NC_081277.1
        - NC_081278.1
        - NC_081279.1
        - NC_081280.1
        - NC_081281.1
        - NC_081282.1
        - NC_081283.1
        - NC_081284.1
        - NC_081285.1
        - NC_081286.1
        - NC_081287.1
        - NC_081288.1
        - NC_081289.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_081249.1
        - NC_081250.1
        - NC_081251.1
        - NC_081252.1
        - NC_081253.1
        - NC_081254.1
        - NC_081255.1
        - NC_081256.1
        - NC_081257.1
        - NC_081258.1
        - NC_081259.1
        - NC_081260.1
        - NC_081261.1
        - NC_081262.1
        - NC_081263.1
        - NC_081264.1
        - NC_081265.1
        - NC_081266.1
        - NC_081267.1
        - NC_081268.1
        - NC_081269.1
        - NC_081270.1
        - NC_081271.1
        - NC_081272.1
        - NC_081273.1
        - NC_081274.1
        - NC_081275.1
        - NC_081276.1
        - NC_081277.1
        - NC_081278.1
        - NC_081279.1
        - NC_081280.1
        - NC_081281.1
        - NC_081282.1
        - NC_081283.1
        - NC_081284.1
        - NC_081285.1
        - NC_081286.1
        - NC_081287.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
