    CLADE : birds 
    SPEC_NAME : PsiEch 
    FULL_SPEC_NAME : Psittacula_echo 
    ALN_NAME : bPsiEch 
    CHROM_START_CHR : OY    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 34
    NUM_ALL_CHR: 35
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - OY725420.1
        - OY725421.1
        - OY725422.1
        - OY725423.1
        - OY725425.1
        - OY725426.1
        - OY725427.1
        - OY725428.1
        - OY725429.1
        - OY725430.1
        - OY725431.1
        - OY725432.1
        - OY725433.1
        - OY725434.1
        - OY725435.1
        - OY725436.1
        - OY725437.1
        - OY725438.1
        - OY725439.1
        - OY725440.1
        - OY725441.1
        - OY725442.1
        - OY725443.1
        - OY725444.1
        - OY725445.1
        - OY725446.1
        - OY725447.1
        - OY725448.1
        - OY725449.1
        - OY725450.1
        - OY725451.1
        - OY725452.1
        - OY725453.1
        - OY725454.1 
        - OY725424.1
    AUTOSOMAL_CHROMOSOMES: 
        - OY725420.1
        - OY725421.1
        - OY725422.1
        - OY725423.1
        - OY725425.1
        - OY725426.1
        - OY725427.1
        - OY725428.1
        - OY725429.1
        - OY725430.1
        - OY725431.1
        - OY725432.1
        - OY725433.1
        - OY725434.1
        - OY725435.1
        - OY725436.1
        - OY725437.1
        - OY725438.1
        - OY725439.1
        - OY725440.1
        - OY725441.1
        - OY725442.1
        - OY725443.1
        - OY725444.1
        - OY725445.1
        - OY725446.1
        - OY725447.1
        - OY725448.1
        - OY725449.1
        - OY725450.1
        - OY725451.1
        - OY725452.1
        - OY725453.1
        - OY725454.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
