    CLADE : birds 
    SPEC_NAME : RhePen 
    FULL_SPEC_NAME : Rhea_pennata 
    ALN_NAME : bRhePen 
    CHROM_START_CHR : NC    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 39
    NUM_ALL_CHR: 40
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_084663.1
        - NC_084664.1
        - NC_084665.1
        - NC_084666.1
        - NC_084667.1
        - NC_084668.1
        - NC_084669.1
        - NC_084670.1
        - NC_084671.1
        - NC_084672.1
        - NC_084673.1
        - NC_084674.1
        - NC_084675.1
        - NC_084676.1
        - NC_084677.1
        - NC_084678.1
        - NC_084679.1
        - NC_084680.1
        - NC_084681.1
        - NC_084682.1
        - NC_084683.1
        - NC_084684.1
        - NC_084685.1
        - NC_084686.1
        - NC_084687.1
        - NC_084688.1
        - NC_084689.1
        - NC_084690.1
        - NC_084691.1
        - NC_084692.1
        - NC_084693.1
        - NC_084694.1
        - NC_084695.1
        - NC_084696.1
        - NC_084697.1
        - NC_084698.1
        - NC_084699.1
        - NC_084700.1
        # - NC_084701.1
        - NC_084702.1 
    AUTOSOMAL_CHROMOSOMES: 
        - NC_084663.1
        - NC_084664.1
        - NC_084665.1
        - NC_084666.1
        - NC_084667.1
        - NC_084668.1
        - NC_084669.1
        - NC_084670.1
        - NC_084671.1
        - NC_084672.1
        - NC_084673.1
        - NC_084674.1
        - NC_084675.1
        - NC_084676.1
        - NC_084677.1
        - NC_084678.1
        - NC_084679.1
        - NC_084680.1
        - NC_084681.1
        - NC_084682.1
        - NC_084683.1
        - NC_084684.1
        - NC_084685.1
        - NC_084686.1
        - NC_084687.1
        - NC_084688.1
        - NC_084689.1
        - NC_084690.1
        - NC_084691.1
        - NC_084692.1
        - NC_084693.1
        - NC_084694.1
        - NC_084695.1
        - NC_084696.1
        - NC_084697.1
        - NC_084698.1
        - NC_084699.1
        - NC_084700.1
        # - NC_084701.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
