    CLADE : birds 
    SPEC_NAME : RisTri 
    FULL_SPEC_NAME : Rissa_tridactyla 
    ALN_NAME : bRisTri 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 30
    NUM_ALL_CHR: 32
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_071466.1
        - NC_071467.1
        - NC_071468.1
        - NC_071469.1
        - NC_071470.1
        - NC_071471.1
        - NC_071472.1
        - NC_071473.1
        - NC_071474.1
        - NC_071475.1
        - NC_071476.1
        - NC_071477.1
        - NC_071478.1
        - NC_071479.1
        - NC_071480.1
        - NC_071481.1
        - NC_071482.1
        - NC_071483.1
        - NC_071484.1
        - NC_071485.1
        - NC_071486.1
        - NC_071487.1
        - NC_071488.1
        - NC_071489.1
        - NC_071490.1
        - NC_071491.1
        - NC_071492.1
        - NC_071493.1
        - NC_071494.1
        - NC_071495.1
        - NC_071496.1
        - NC_071497.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_071466.1
        - NC_071467.1
        - NC_071468.1
        - NC_071469.1
        - NC_071470.1
        - NC_071471.1
        - NC_071472.1
        - NC_071473.1
        - NC_071474.1
        - NC_071475.1
        - NC_071476.1
        - NC_071477.1
        - NC_071478.1
        - NC_071479.1
        - NC_071480.1
        - NC_071481.1
        - NC_071482.1
        - NC_071483.1
        - NC_071484.1
        - NC_071485.1
        - NC_071486.1
        - NC_071487.1
        - NC_071488.1
        - NC_071489.1
        - NC_071490.1
        - NC_071491.1
        - NC_071492.1
        - NC_071493.1
        - NC_071494.1
        - NC_071495.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
