    CLADE : birds 
    SPEC_NAME : StrCam 
    FULL_SPEC_NAME : Struthio_camelus  
    ALN_NAME : bStrCam 
    CHROM_START_CHR : NC
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 39
    NUM_ALL_CHR: 41
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_090942.1
        - NC_090943.1
        - NC_090944.1
        - NC_090945.1
        - NC_090946.1
        - NC_090947.1
        - NC_090948.1
        - NC_090949.1
        - NC_090950.1
        - NC_090951.1
        - NC_090952.1
        - NC_090953.1
        - NC_090954.1
        - NC_090955.1
        - NC_090956.1
        - NC_090957.1
        - NC_090958.1
        - NC_090959.1
        - NC_090960.1
        - NC_090961.1
        - NC_090962.1
        - NC_090963.1
        - NC_090964.1
        - NC_090965.1
        - NC_090966.1
        - NC_090967.1
        - NC_090968.1
        - NC_090969.1
        - NC_090970.1
        - NC_090971.1
        - NC_090972.1
        - NC_090973.1
        - NC_090974.1
        - NC_090975.1
        - NC_090976.1
        - NC_090977.1
        - NC_090978.1
        - NC_090979.1
        - NC_090980.1
        - NC_090981.1
        - NC_090982.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_090942.1
        - NC_090943.1
        - NC_090944.1
        - NC_090945.1
        - NC_090946.1
        - NC_090947.1
        - NC_090948.1
        - NC_090949.1
        - NC_090950.1
        - NC_090951.1
        - NC_090952.1
        - NC_090953.1
        - NC_090954.1
        - NC_090955.1
        - NC_090956.1
        - NC_090957.1
        - NC_090958.1
        - NC_090959.1
        - NC_090960.1
        - NC_090961.1
        - NC_090962.1
        - NC_090963.1
        - NC_090964.1
        - NC_090965.1
        - NC_090966.1
        - NC_090967.1
        - NC_090968.1
        - NC_090969.1
        - NC_090970.1
        - NC_090971.1
        - NC_090972.1
        - NC_090973.1
        - NC_090974.1
        - NC_090975.1
        - NC_090976.1
        - NC_090977.1
        - NC_090978.1
        - NC_090979.1
        - NC_090980.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
