    CLADE : birds 
    SPEC_NAME : StrTur 
    FULL_SPEC_NAME : Streptopelia_turtur 
    ALN_NAME : bStrTur 
    CHROM_START_CHR : LR    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 33
    NUM_ALL_CHR: 35
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - LR594551.2
        - LR594552.1
        - LR594553.2
        - LR594554.2
        - LR594556.1
        - LR594558.1
        - LR594557.1
        - LR594559.1
        - LR594560.2
        - LR594562.1
        - LR594563.1
        - LR594561.1
        - LR594564.1
        - LR594565.1
        - LR594567.2
        - LR594569.2
        - LR594570.2
        - LR594568.1
        - LR594566.1
        - LR594571.2
        - LR594577.1
        - LR594572.1
        - LR594573.1
        - LR594579.1
        - LR594575.2
        - LR594576.2
        - LR594574.2
        - OU015479.1
        - LR594580.2
        - LR594581.1
        - LR594578.1
        - LR594555.2
    AUTOSOMAL_CHROMOSOMES: 
        - LR594551.2
        - LR594552.1
        - LR594553.2
        - LR594554.2
        - LR594556.1
        - LR594558.1
        - LR594557.1
        - LR594559.1
        - LR594560.2
        - LR594562.1
        - LR594563.1
        - LR594561.1
        - LR594564.1
        - LR594565.1
        - LR594567.2
        - LR594569.2
        - LR594570.2
        - LR594568.1
        - LR594566.1
        - LR594571.2
        - LR594577.1
        - LR594572.1
        - LR594573.1
        - LR594579.1
        - LR594575.2
        - LR594576.2
        - LR594574.2
        - OU015479.1
        - LR594580.2
        - LR594581.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
