    CLADE : birds 
    SPEC_NAME : VidCha 
    FULL_SPEC_NAME : Vidua_chalybeata 
    ALN_NAME : bVidCha 
    CHROM_START_CHR : NC    
    WINDOW_INTERVAL : 500000 
    WINDOW_LENGTH : 1000000 
    NUM_AUT_CHROMOSOMES : 39
    NUM_ALL_CHR: 41
    MUTATION_RATE: 1.25e-8 
    GENERATION_TIME: 
    ALL_CHROMOSOMES : 
        - NC_071530.1
        - NC_071531.1
        - NC_071532.1
        - NC_071533.1
        - NC_071534.1
        - NC_071535.1
        - NC_071536.1
        - NC_071537.1
        - NC_071538.1
        - NC_071539.1
        - NC_071540.1
        - NC_071541.1
        - NC_071542.1
        - NC_071543.1
        - NC_071544.1
        - NC_071545.1
        - NC_071546.1
        - NC_071547.1
        - NC_071548.1
        - NC_071549.1
        - NC_071550.1
        - NC_071551.1
        - NC_071552.1
        - NC_071553.1
        - NC_071554.1
        - NC_071555.1
        - NC_071556.1
        - NC_071557.1
        - NC_071558.1
        - NC_071559.1
        - NC_071560.1
        - NC_071561.1
        - NC_071562.1
        - NC_071563.1
        - NC_071564.1
        - NC_071565.1
        - NC_071566.1
        - NC_071567.1
        - NC_071568.1
        - NC_071569.1
        - NC_071570.1
    AUTOSOMAL_CHROMOSOMES: 
        - NC_071530.1
        - NC_071531.1
        - NC_071532.1
        - NC_071533.1
        - NC_071534.1
        - NC_071535.1
        - NC_071536.1
        - NC_071537.1
        - NC_071538.1
        - NC_071539.1
        - NC_071540.1
        - NC_071541.1
        - NC_071542.1
        - NC_071543.1
        - NC_071544.1
        - NC_071545.1
        - NC_071546.1
        - NC_071547.1
        - NC_071548.1
        - NC_071549.1
        - NC_071550.1
        - NC_071551.1
        - NC_071552.1
        - NC_071553.1
        - NC_071554.1
        - NC_071555.1
        - NC_071556.1
        - NC_071557.1
        - NC_071558.1
        - NC_071559.1
        - NC_071560.1
        - NC_071561.1
        - NC_071562.1
        - NC_071563.1
        - NC_071564.1
        - NC_071565.1
        - NC_071566.1
        - NC_071567.1
        - NC_071568.1
    BOOTSTRAPPING_VALUES: 
        - 0 
        - 1 
        - 2 
        - 3 
        - 4 
        - 5 
        - 6 
        - 7 
        - 8 
        - 9 
        - 10 
        - 11 
        - 12 
        - 13 
        - 14 
        - 15 
        - 16 
        - 17 
        - 18 
        - 19 
        - 20 
        - 21 
        - 22 
        - 23 
        - 24 
        - 25 
        - 26 
        - 27 
        - 28 
        - 29 
